# Generated by Django 3.2.6 on 2021-09-02 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=-1)),
                ('value_reverse', models.FloatField(default=-1)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='matches',
            constraint=models.CheckConstraint(check=models.Q(('user1__lt', django.db.models.expressions.F('user2'))), name='matches_user_id1_lt_id2'),
        ),
        migrations.AddConstraint(
            model_name='matches',
            constraint=models.UniqueConstraint(fields=('user1', 'user2'), name='matches_user_relation_unique'),
        ),
    ]
