# Generated by Django 3.2.6 on 2021-09-04 12:50

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='auth.user')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('user_avatar', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('location_city', models.CharField(blank=True, max_length=30, null=True)),
                ('location_state', models.CharField(blank=True, max_length=30, null=True)),
                ('location_country', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female'), (2, 'Non-binary'), (3, 'Female Transgender'), (4, 'Male Transgender')], null=True)),
                ('sexual_orientation', models.IntegerField(blank=True, choices=[(0, 'Straight'), (1, 'Gay'), (2, 'Lesbian'), (3, 'Bisexual'), (4, 'Pansexual'), (5, 'Queer')], null=True)),
                ('education', models.IntegerField(blank=True, choices=[(0, 'High School'), (1, 'Trade School'), (2, 'Some College'), (3, 'Undergraduate Degree'), (4, 'Graduate Degree')], null=True)),
                ('religion', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Catholic'), (1, 'Christian'), (2, 'Orthodox Jewish'), (3, 'Non-orthodox Jewish'), (4, 'Buddhist'), (5, 'Mormon'), (6, 'Hindu'), (7, 'Sikh'), (8, 'Atheist'), (9, 'Agnostic'), (10, 'Muslim'), (11, 'Other')], max_length=25, null=True)),
                ('children', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'No children'), (1, 'Small children'), (2, 'Pre-teen/Teen children'), (3, 'Adult children')], max_length=7, null=True)),
                ('destination', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Relationship'), (1, 'Something casual'), (2, 'I don’t know yet'), (3, 'Marriage')], max_length=7, null=True)),
                ('question1', models.CharField(blank=True, max_length=300, null=True)),
                ('question2', models.CharField(blank=True, max_length=300, null=True)),
                ('question3', models.CharField(blank=True, max_length=300, null=True)),
                ('question4', models.CharField(blank=True, max_length=300, null=True)),
                ('question5', models.CharField(blank=True, max_length=300, null=True)),
                ('question6', models.CharField(blank=True, max_length=300, null=True)),
                ('stamp_count', jsonfield.fields.JSONField(blank=True, null=True)),
                ('selected_stamps', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'None'), (1, 'Abandonment'), (2, 'Avoidant'), (3, 'Workaholic'), (4, 'Dramatic'), (5, 'Cheapskate'), (6, 'Hypersensitive'), (7, 'Cigarette Smoker'), (8, 'Overwhelmed'), (9, 'Unrefined'), (10, 'Loner'), (11, 'Stagnant'), (12, 'Negativenat'), (13, 'Perfectionist'), (14, 'Unreliable'), (15, 'Wildcard'), (16, 'Noboundaries'), (17, 'Selfcentered'), (18, 'Poor Communicator'), (19, 'Trust Issues'), (20, 'Resentful')], max_length=52, null=True)),
                ('filled_claims', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.CheckConstraint(check=models.Q(('age__gte', 18)), name='userprofile_age_gt_18'),
        ),
    ]
