# Generated by Django 3.2.13 on 2022-05-14 04:39

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_avatar',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='religion',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Catholic'), (1, 'Christian'), (2, 'Orthodox Jewish'), (3, 'Non-Orthodox Jewish'), (4, 'Buddhist'), (5, 'Mormon'), (6, 'Hindu'), (7, 'Sikh'), (8, 'Atheist'), (9, 'Agnostic'), (10, 'Muslim'), (11, 'Other')], max_length=25, null=True),
        ),
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='profile/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_photos', to='profiles.userprofile')),
            ],
        ),
    ]
