# Generated by Django 3.2.13 on 2022-05-14 04:39

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim1',
            name='Q28A',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Catholic'), (1, 'Christian'), (2, 'Orthodox Jewish'), (3, 'Non-Orthodox Jewish'), (4, 'Buddhist'), (5, 'Mormon'), (6, 'Hindu'), (7, 'Sikh'), (8, 'Atheist'), (9, 'Agnostic'), (10, 'Muslim'), (11, 'Other')], default=None, max_length=25, null=True),
        ),
    ]
