# Generated by Django 3.2.13 on 2022-05-14 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_alter_claim1_q28a'),
        ('claims', '0002_auto_20220514_1328'),
    ]

    operations = [
    ]
