from profiles.models import Stamps

stamps = {
    'Q1A': (Stamps.OVERWHELMED, Stamps.NOBOUNDARIES),
    'Q2A': (Stamps.OVERWHELMED, Stamps.LONER,Stamps.STAGNANT,Stamps.PERFECTIONIST,Stamps.WILDCARD,Stamps.SELFCENTERED),
    'Q3A': (Stamps.CHEAPSKATE, Stamps.WILDCARD,Stamps.TRUSTISSUES),
    'Q4A': (Stamps.AVOIDANT, Stamps.LONER, Stamps.SELFCENTERED,Stamps.POORCOMMUNICATOR),
    'Q5A': (Stamps.AVOIDANT, Stamps.PERFECTIONIST,Stamps.WILDCARD, Stamps.NOBOUNDARIES, Stamps.SELFCENTERED),
    'Q6A': (Stamps.AVOIDANT, Stamps.WORKAHOLIC, Stamps.CHEAPSKATE, Stamps.OVERWHELMED, Stamps.STAGNANT, Stamps.NEGATIVENAT, Stamps.WILDCARD, Stamps.SELFCENTERED, Stamps.TRUSTISSUES,Stamps.RESENTFUL),
    'Q7A': (Stamps.OVERWHELMED, Stamps.PERFECTIONIST, Stamps.NOBOUNDARIES,Stamps.SELFCENTERED),
    'Q8A': (Stamps.AVOIDANT, Stamps.OVERWHELMED,Stamps.UNREFINED, Stamps.STAGNANT, Stamps.SELFCENTERED),
    'Q9A': (Stamps.AVOIDANT, Stamps.CHEAPSKATE,Stamps.HYPERSENSITIVE, Stamps.OVERWHELMED, Stamps.STAGNANT),
    'Q10A': (Stamps.NOBOUNDARIES, Stamps.SELFCENTERED),
    'Q11A': (Stamps.WILDCARD,),
    'Q12A': (Stamps.OVERWHELMED, Stamps.WILDCARD, Stamps.NOBOUNDARIES, Stamps.SELFCENTERED, Stamps.RESENTFUL),
    'Q13A': (Stamps.CIGARETTESMOKER, Stamps.OVERWHELMED, Stamps.NOBOUNDARIES,Stamps.SELFCENTERED),
    'Q14A': (Stamps.UNREFINED, Stamps.STAGNANT),
    'Q15A': (Stamps.OVERWHELMED,Stamps.UNREFINED, Stamps.STAGNANT),
    'Q16A': (Stamps.AVOIDANT, Stamps.OVERWHELMED,Stamps.UNREFINED, Stamps.STAGNANT, Stamps.SELFCENTERED),
    'Q17A': (Stamps.AVOIDANT, Stamps.OVERWHELMED, Stamps.LONER,Stamps.NOBOUNDARIES),
    'Q18A': (),
    'Q19A': (Stamps.AVOIDANT, Stamps.HYPERSENSITIVE, Stamps.OVERWHELMED, Stamps.STAGNANT,Stamps.NOBOUNDARIES),
    'Q20A': (Stamps.STAGNANT, Stamps.NOBOUNDARIES),
    'Q21A': (Stamps.HYPERSENSITIVE,),
    'Q22A': (Stamps.STAGNANT, Stamps.PERFECTIONIST, Stamps.NOBOUNDARIES, Stamps.SELFCENTERED),
    'Q23A': (),
    'Q24A': (Stamps.CHEAPSKATE, Stamps.UNREFINED, Stamps.NEGATIVENAT, Stamps.SELFCENTERED),
    'Q25A': (Stamps.NOBOUNDARIES,),
    'Q26A': (Stamps.OVERWHELMED, Stamps.PERFECTIONIST, Stamps.SELFCENTERED),
    'Q27A': (Stamps.DRAMATIC, Stamps.HYPERSENSITIVE, Stamps.NEGATIVENAT, Stamps.NOBOUNDARIES, Stamps.SELFCENTERED, Stamps.RESENTFUL),
    'Q28A': (Stamps.DRAMATIC, Stamps.HYPERSENSITIVE, Stamps.STAGNANT, Stamps.NEGATIVENAT, Stamps.PERFECTIONIST, Stamps.NOBOUNDARIES, Stamps.SELFCENTERED, Stamps.RESENTFUL),
    'Q29A': (Stamps.WORKAHOLIC,Stamps.NOBOUNDARIES, Stamps.SELFCENTERED),
    'Q30A': (Stamps.AVOIDANT, Stamps.UNRELIABLE, Stamps.WILDCARD,Stamps.NOBOUNDARIES, Stamps.SELFCENTERED),
    'Q31A': (Stamps.WILDCARD, Stamps.NOBOUNDARIES, Stamps.SELFCENTERED),
    'Q32A': (Stamps.NOBOUNDARIES, Stamps.SELFCENTERED),
    'Q33A': (Stamps.DRAMATIC, Stamps.OVERWHELMED, Stamps.NEGATIVENAT, Stamps.PERFECTIONIST, Stamps.NOBOUNDARIES, Stamps.SELFCENTERED,Stamps.POORCOMMUNICATOR, Stamps.RESENTFUL),
    'Q34A': (Stamps.ABANDONMENT, Stamps.DRAMATIC, Stamps.HYPERSENSITIVE, Stamps.OVERWHELMED, Stamps.NEGATIVENAT, Stamps.NOBOUNDARIES, Stamps.SELFCENTERED, Stamps.POORCOMMUNICATOR, Stamps.TRUSTISSUES, Stamps.RESENTFUL),
    'Q35A': (Stamps.AVOIDANT,Stamps.OVERWHELMED, Stamps.LONER, Stamps.SELFCENTERED),
    'Q36A': (Stamps.AVOIDANT, Stamps.OVERWHELMED,Stamps.UNRELIABLE, Stamps.WILDCARD, Stamps.NOBOUNDARIES, Stamps.SELFCENTERED),
    'Q37A': (Stamps.AVOIDANT, Stamps.OVERWHELMED,Stamps.STAGNANT, Stamps.NOBOUNDARIES, Stamps.SELFCENTERED),
    'Q38A': (Stamps.AVOIDANT,Stamps.OVERWHELMED, Stamps.UNREFINED, Stamps.STAGNANT, Stamps.SELFCENTERED, Stamps.POORCOMMUNICATOR),
    'Q39A': (Stamps.AVOIDANT, Stamps.OVERWHELMED, Stamps.UNREFINED, Stamps.STAGNANT, Stamps.SELFCENTERED,Stamps.POORCOMMUNICATOR),
    'Q40A': (Stamps.AVOIDANT, Stamps.OVERWHELMED, Stamps.UNREFINED, Stamps.LONER, Stamps.STAGNANT, Stamps.SELFCENTERED,Stamps.POORCOMMUNICATOR),
    'Q41A': (Stamps.AVOIDANT, Stamps.OVERWHELMED, Stamps.UNREFINED,Stamps.LONER, Stamps.STAGNANT, Stamps.POORCOMMUNICATOR),
    'Q42A': (Stamps.DRAMATIC, Stamps.HYPERSENSITIVE, Stamps.OVERWHELMED, Stamps.UNREFINED, Stamps.NEGATIVENAT, Stamps.PERFECTIONIST, Stamps.NOBOUNDARIES, Stamps.SELFCENTERED,Stamps.POORCOMMUNICATOR, Stamps.RESENTFUL),
    'Q42B': (Stamps.OVERWHELMED,),
    'Q43A': (Stamps.WILDCARD,),
    'Q44A': (Stamps.AVOIDANT, Stamps.OVERWHELMED, Stamps.LONER,Stamps.STAGNANT),
    'Q44B': (Stamps.NOBOUNDARIES,),
    'Q45A': (Stamps.AVOIDANT, Stamps.OVERWHELMED,Stamps.NOBOUNDARIES, Stamps.POORCOMMUNICATOR),
    'Q46A': (Stamps.AVOIDANT, Stamps.OVERWHELMED, Stamps.STAGNANT,Stamps.PERFECTIONIST, Stamps.WILDCARD, Stamps.TRUSTISSUES),
    'Q46B': (Stamps.ABANDONMENT, Stamps.HYPERSENSITIVE, Stamps.NEGATIVENAT, Stamps.PERFECTIONIST, Stamps.SELFCENTERED,Stamps.TRUSTISSUES),
    'Q47A': (Stamps.ABANDONMENT, Stamps.AVOIDANT, Stamps.OVERWHELMED, Stamps.UNREFINED, Stamps.LONER, Stamps.STAGNANT, Stamps.NEGATIVENAT, Stamps.UNRELIABLE, Stamps.NOBOUNDARIES, Stamps.SELFCENTERED, Stamps.POORCOMMUNICATOR),
    'Q47B': (Stamps.ABANDONMENT, Stamps.HYPERSENSITIVE, Stamps.OVERWHELMED, Stamps.NEGATIVENAT, Stamps.PERFECTIONIST, Stamps.SELFCENTERED, Stamps.TRUSTISSUES, Stamps.RESENTFUL),
    'Q48A': (Stamps.ABANDONMENT,Stamps.HYPERSENSITIVE, Stamps.NEGATIVENAT, Stamps.TRUSTISSUES),
    'Q49A': (Stamps.AVOIDANT, Stamps.NEGATIVENAT, Stamps.UNRELIABLE, Stamps.WILDCARD, Stamps.NOBOUNDARIES,Stamps.SELFCENTERED, Stamps.POORCOMMUNICATOR),
    'Q50A': (Stamps.DRAMATIC, Stamps.HYPERSENSITIVE,Stamps.OVERWHELMED, Stamps.UNREFINED, Stamps.NOBOUNDARIES, Stamps.SELFCENTERED, Stamps.POORCOMMUNICATOR, Stamps.RESENTFUL),
    'Q51A': (Stamps.ABANDONMENT,Stamps.AVOIDANT, Stamps.PERFECTIONIST, Stamps.NOBOUNDARIES, Stamps.SELFCENTERED, Stamps.RESENTFUL),
    'Q52A': (Stamps.AVOIDANT, Stamps.HYPERSENSITIVE, Stamps.OVERWHELMED, Stamps.STAGNANT, Stamps.NEGATIVENAT, Stamps.UNRELIABLE, Stamps.WILDCARD, Stamps.NOBOUNDARIES, Stamps.SELFCENTERED,Stamps.POORCOMMUNICATOR, Stamps.RESENTFUL),
    'Q53A': (Stamps.AVOIDANT, Stamps.HYPERSENSITIVE, Stamps.OVERWHELMED, Stamps.STAGNANT, Stamps.NEGATIVENAT, Stamps.UNRELIABLE, Stamps.WILDCARD, Stamps.NOBOUNDARIES, Stamps.SELFCENTERED,Stamps.POORCOMMUNICATOR, Stamps.RESENTFUL),
    'Q54A': (Stamps.AVOIDANT,Stamps.OVERWHELMED, Stamps.LONER, Stamps.PERFECTIONIST, Stamps.SELFCENTERED, Stamps.POORCOMMUNICATOR),
    'Q55A': (Stamps.AVOIDANT, Stamps.OVERWHELMED, Stamps.PERFECTIONIST, Stamps.SELFCENTERED),
    'Q56A': (Stamps.DRAMATIC, Stamps.NOBOUNDARIES, Stamps.SELFCENTERED,Stamps.POORCOMMUNICATOR),
    'Q57A': (Stamps.ABANDONMENT, Stamps.HYPERSENSITIVE, Stamps.NEGATIVENAT, Stamps.PERFECTIONIST),
    'Q58A': (Stamps.ABANDONMENT, Stamps.DRAMATIC, Stamps.HYPERSENSITIVE, Stamps.OVERWHELMED, Stamps.NEGATIVENAT, Stamps.NOBOUNDARIES,Stamps.SELFCENTERED, Stamps.TRUSTISSUES),
    'Q59A': (Stamps.HYPERSENSITIVE, Stamps.NEGATIVENAT,Stamps.TRUSTISSUES, Stamps.RESENTFUL),
    'Q60A': (Stamps.AVOIDANT, Stamps.HYPERSENSITIVE, Stamps.NOBOUNDARIES,Stamps.RESENTFUL),
    'Q61A': (Stamps.AVOIDANT, Stamps.OVERWHELMED, Stamps.NEGATIVENAT, Stamps.SELFCENTERED,Stamps.POORCOMMUNICATOR),
    'Q62A': (Stamps.AVOIDANT, Stamps.OVERWHELMED, Stamps.UNREFINED, Stamps.STAGNANT, Stamps.SELFCENTERED,Stamps.POORCOMMUNICATOR),
    'Q63A': (Stamps.AVOIDANT, Stamps.OVERWHELMED, Stamps.LONER, Stamps.SELFCENTERED),
    'Q64A': (Stamps.ABANDONMENT,Stamps.DRAMATIC,Stamps.HYPERSENSITIVE,Stamps.TRUSTISSUES, Stamps.RESENTFUL),
    'Q65A': (Stamps.ABANDONMENT, Stamps.DRAMATIC, Stamps.HYPERSENSITIVE, Stamps.NEGATIVENAT, Stamps.SELFCENTERED, Stamps.TRUSTISSUES,Stamps.RESENTFUL),
    'Q66A': (Stamps.AVOIDANT, Stamps.OVERWHELMED, Stamps.PERFECTIONIST,Stamps.RESENTFUL),
    'Q67A': (Stamps.AVOIDANT, Stamps.DRAMATIC, Stamps.PERFECTIONIST, Stamps.RESENTFUL),
    'Q68A': (Stamps.ABANDONMENT, Stamps.DRAMATIC, Stamps.HYPERSENSITIVE,Stamps.NEGATIVENAT, Stamps.PERFECTIONIST, Stamps.TRUSTISSUES),
    'Q69A': (Stamps.AVOIDANT,Stamps.OVERWHELMED, Stamps.STAGNANT, Stamps.PERFECTIONIST, Stamps.SELFCENTERED, Stamps.RESENTFUL),
    'Q70A': (Stamps.ABANDONMENT, Stamps.PERFECTIONIST,Stamps.TRUSTISSUES),
    'Q71A': (Stamps.ABANDONMENT,Stamps.HYPERSENSITIVE, Stamps.NEGATIVENAT, Stamps.TRUSTISSUES),
    'Q72A': (Stamps.ABANDONMENT, Stamps.AVOIDANT, Stamps.HYPERSENSITIVE,Stamps.NEGATIVENAT, Stamps.TRUSTISSUES, Stamps.RESENTFUL),
    'Q73A': (Stamps.ABANDONMENT, Stamps.HYPERSENSITIVE, Stamps.NEGATIVENAT, Stamps.PERFECTIONIST,Stamps.SELFCENTERED, Stamps.TRUSTISSUES, Stamps.RESENTFUL),
    'Q74A': (Stamps.ABANDONMENT, Stamps.AVOIDANT, Stamps.DRAMATIC, Stamps.HYPERSENSITIVE, Stamps.OVERWHELMED, Stamps.NEGATIVENAT,Stamps.PERFECTIONIST, Stamps.SELFCENTERED, Stamps.RESENTFUL),
    'Q75A': (Stamps.PERFECTIONIST, Stamps.SELFCENTERED, Stamps.RESENTFUL),
    'Q76A': (Stamps.ABANDONMENT, Stamps.AVOIDANT,Stamps.NOBOUNDARIES),
    'Q77A': (Stamps.AVOIDANT, Stamps.SELFCENTERED, Stamps.POORCOMMUNICATOR),
    'Q78A': (Stamps.AVOIDANT, Stamps.NEGATIVENAT, Stamps.PERFECTIONIST, Stamps.SELFCENTERED),
    'Q78B': (Stamps.AVOIDANT, Stamps.HYPERSENSITIVE,Stamps.OVERWHELMED, Stamps.STAGNANT),
    'Q79A': (Stamps.PERFECTIONIST,Stamps.SELFCENTERED),
    'Q79B': (Stamps.ABANDONMENT, Stamps.AVOIDANT, Stamps.WILDCARD),
    'Q80A': (Stamps.AVOIDANT, Stamps.SELFCENTERED),
    'Q81A': (Stamps.DRAMATIC, Stamps.HYPERSENSITIVE, Stamps.OVERWHELMED, Stamps.SELFCENTERED, Stamps.POORCOMMUNICATOR),
    'Q81B': (Stamps.ABANDONMENT, Stamps.DRAMATIC,Stamps.OVERWHELMED, Stamps.NEGATIVENAT, Stamps.POORCOMMUNICATOR),
    'Q82A': (Stamps.AVOIDANT,Stamps.POORCOMMUNICATOR),
    'Q83A': (Stamps.AVOIDANT,Stamps.OVERWHELMED, Stamps.SELFCENTERED, Stamps.POORCOMMUNICATOR),
    'Q84A': (Stamps.DRAMATIC, Stamps.UNREFINED),
    'Q85A': (Stamps.SELFCENTERED,),
    'Q86A': (Stamps.PERFECTIONIST, Stamps.SELFCENTERED),
    'Q86B': (Stamps.ABANDONMENT, Stamps.PERFECTIONIST,Stamps.SELFCENTERED),
    'Q87A': (Stamps.ABANDONMENT, Stamps.HYPERSENSITIVE),
    'Q87B': (Stamps.PERFECTIONIST,Stamps.SELFCENTERED),
    'Q88A': (Stamps.DRAMATIC,Stamps.NEGATIVENAT, Stamps.PERFECTIONIST, Stamps.SELFCENTERED),
    'Q89A': (Stamps.ABANDONMENT, Stamps.AVOIDANT, Stamps.DRAMATIC,Stamps.HYPERSENSITIVE, Stamps.OVERWHELMED, Stamps.NEGATIVENAT),
}

relationships = {
    'Q1A': {
        'Q37A': lambda a, b: -1 if a and b else 0,
        'Q63A': lambda a, b: -1 if a and b else 0,
        'Q35A': lambda a, b: -1 if a and b else 0,
        'Q39A': lambda a, b: -1 if a and b else 0,
        'Q47B': lambda a, b: 1 if a and b else 0,
        'Q10A': lambda a, b: -1 if a and b else 0,
        'Q34A': lambda a, b: 2 if a and b else 0,
        'Q7A': lambda a, b: 1 if a and b else 0,
        'Q33A': lambda a, b: 1 if a and b else 0,
        'Q32A': lambda a, b: 2 if a and b else 0,
        'Q36A': lambda a, b: 1 if a and b else 0,
        'Q50A': lambda a, b: 2 if a and b else 0,
        'Q75A': lambda a, b: 2 if a and b else 0,
        'Q81A': lambda a, b: 1 if a and b else 0,
        'Q86B': lambda a, b: 1 if a and b else 0,
        'Q58A': lambda a, b: 1 if a and b else 0,
        'Q59A': lambda a, b: -1 if a and b else 0,
        'Q64A': lambda a, b: 1 if a and b else 0,
        'Q65A': lambda a, b: 1 if a and b else 0,
        'Q73A': lambda a, b: 1 if a and b else 0,
        'Q74A': lambda a, b: 1 if a and b else 0,
        'Q3A': lambda a, b: -2 if a and b else 0,
        'Q2A': lambda a, b: 2 if a and b else 0,
        'Q1A': lambda a, b: -2 if a and b else 0,
    },
    'Q2A': {
        'Q46A': lambda a, b: -2 if a and b else 0,
        'Q3A': lambda a, b: -2 if a and b else 0,
        'Q2A': lambda a, b: -2 if a and b else 0,
        'Q29A': lambda a, b: -1 if a and b else 0,
        'Q32A': lambda a, b: -1 if a and b else 0,
        'Q58A': lambda a, b: -1 if a and b else 0,
        'Q63A': lambda a, b: -1 if a and b else 0,
        'Q64A': lambda a, b: -2 if a and b else 0,
        'Q80A': lambda a, b: 1 if a and b else 0,
        'Q86B': lambda a, b: -2 if a and b else 0,
        'Q89A': lambda a, b: -1 if a and b else 0,
        'Q33A': lambda a, b: 2 if a and b else 0,
        'Q1A': lambda a, b: 2 if a and b else 0,
        'Q18A': lambda a, b: -1 if a and b else 0,
    },
    'Q3A': {
        'Q46A': lambda a, b: 0.5 if a and b else 0,
        'Q1A': lambda a, b: -2 if a and b else 0,
        'Q2A': lambda a, b: -2 if a and b else 0,
        'Q3A': lambda a, b: -2 if a and b else 0,
        'Q10A': lambda a, b: -2 if a and b else 0,
        'Q4A': lambda a, b: -0.5 if a and b else 0,
        'Q14A': lambda a, b: -0.5 if a and b else 0,
        'Q17A': lambda a, b: -0.5 if a and b else 0,
        'Q19A': lambda a, b: -0.5 if a and b else 0,
        'Q20A': lambda a, b: -0.5 if a and b else 0,
        'Q34A': lambda a, b: -0.5 if a and b else 0,
        'Q37A': lambda a, b: -0.5 if a and b else 0,
        'Q58A': lambda a, b: -0.5 if a and b else 0,
        'Q59A': lambda a, b: -0.5 if a and b else 0,
        'Q64A': lambda a, b: -0.5 if a and b else 0,
        'Q75A': lambda a, b: -0.5 if a and b else 0,
        'Q85A': lambda a, b: -0.5 if a and b else 0,
        'Q86A': lambda a, b: -0.5 if a and b else 0,
    },
    'Q4A': {
        'Q58A': lambda a, b: 0.5 if a and b else 0,
        'Q64A': lambda a, b: 0.5 if a and b else 0,
        'Q75A': lambda a, b: 0.5 if a and b else 0,
        'Q56A': lambda a, b: 0.5 if a and b else 0,
        'Q50A': lambda a, b: 0.5 if a and b else 0,
        'Q26A': lambda a, b: 2 if a and b else 0,
        'Q4A': lambda a, b: -2 if a and b else 0,
        'Q46A': lambda a, b: -2 if a and b else 0,
        'Q29A': lambda a, b: -0.5 if a and b else 0,
        'Q35A': lambda a, b: -0.5 if a and b else 0,
        'Q76A': lambda a, b: -0.5 if a and b else 0,
        'Q17A': lambda a, b: -0.5 if a and b else 0,
        'Q63A': lambda a, b: -0.5 if a and b else 0,
        'Q10A': lambda a, b: -0.5 if a and b else 0,
        'Q3A': lambda a, b: -0.5 if a and b else 0,
    },
    'Q5A': {
        'Q5A': lambda a, b: -2 if a and b else 0,
        'Q73A': lambda a, b: 2 if a and b else 0,
        'Q64A': lambda a, b: 2 if a and b else 0,
        'Q69A': lambda a, b: 2 if a and b else 0,
        'Q70A': lambda a, b: 2 if a and b else 0,
        'Q71A': lambda a, b: 2 if a and b else 0,
        'Q72A': lambda a, b: 2 if a and b else 0,
        'Q76A': lambda a, b: 1.5 if a and b else 0,
        'Q77A': lambda a, b: 2 if a and b else 0,
        'Q78A': lambda a, b: 2 if a and b else 0,
        'Q78B': lambda a, b: 2 if a and b else 0,
        'Q58A': lambda a, b: 2 if a and b else 0,
        'Q19A': lambda a, b: 2 if a and b else 0,
        'Q34A': lambda a, b: 2 if a and b else 0,
        'Q35A': lambda a, b: 2 if a and b else 0,
        'Q67A': lambda a, b: 2 if a and b else 0,
        'Q20A': lambda a, b: 1.5 if a and b else 0,
        'Q46B': lambda a, b: 1.5 if a and b else 0,
        'Q30A': lambda a, b: -2 if a and b else 0,
        'Q31A': lambda a, b: -2 if a and b else 0,
        'Q46A': lambda a, b: -2 if a and b else 0,
        'Q56A': lambda a, b: -2 if a and b else 0,
        'Q36A': lambda a, b: -2 if a and b else 0,
        'Q37A': lambda a, b: -2 if a and b else 0,
        'Q68A': lambda a, b: -2 if a and b else 0,
    },
    'Q6A': {
        'Q46A': lambda a, b: -2 if a and b else 0,
        'Q6A': lambda a, b: -2 if a and b else 0,
        'Q46B': lambda a, b: 1 if a and b else 0,
        'Q58A': lambda a, b: 1 if a and b else 0,
    },
    'Q7A': {
        'Q18A': lambda a, b: -0.5 if a and b else 0,
        'Q16A': lambda a, b: 2 if a and b else 0,
        'Q14A': lambda a, b: 2 if a and b else 0,
        'Q89A': lambda a, b: -0.5 if a and b else 0,
        'Q7A': lambda a, b: -2 if a and b else 0,
        'Q2A': lambda a, b: -0.5 if a and b else 0,
        'Q1A': lambda a, b: 0.5 if a and b else 0,
        'Q8A': lambda a, b: 2 if a and b else 0,
        'Q47A': lambda a, b: 0.5 if a and b else 0,
        'Q47B': lambda a, b: -0.5 if a and b else 0,
        'Q75A': lambda a, b: 0.5 if a and b else 0,
        'Q76A': lambda a, b: -2 if a and b else 0,
        'Q78B': lambda a, b: 0.5 if a and b else 0,
        'Q78A': lambda a, b: -0.5 if a and b else 0,
        'Q80A': lambda a, b: 0.5 if a and b else 0,
        'Q83A': lambda a, b: 2 if a and b else 0,
        'Q88A': lambda a, b: -0.5 if a and b else 0,
    },
    'Q8A': {
        'Q1A': lambda a, b: -0.5 if a and b else 0,
        'Q2A': lambda a, b: 0.5 if a and b else 0,
        'Q7A': lambda a, b: 2 if a and b else 0,
        'Q8A': lambda a, b: -2 if a and b else 0,
        'Q14A': lambda a, b: -0.5 if a and b else 0,
        'Q16A': lambda a, b: -0.5 if a and b else 0,
        'Q33A': lambda a, b: 0.5 if a and b else 0,
        'Q78A': lambda a, b: 0.5 if a and b else 0,
        'Q88A': lambda a, b: 0.5 if a and b else 0,
    },
    'Q9A': {
        'Q9A': lambda a, b: -2 if a and b else 0,
        'Q11A': lambda a, b: 0.5 if a and b else 0,
        'Q15A': lambda a, b: -2 if a and b else 0,
        'Q76A': lambda a, b: -2 if a and b else 0,
        'Q24A': lambda a, b: -0.5 if a and b else 0,
        'Q78A': lambda a, b: 2 if a and b else 0,
        'Q25A': lambda a, b: 2 if a and b else 0,
        'Q79A': lambda a, b: 2 if a and b else 0,
        'Q88A': lambda a, b: 0.5 if a and b else 0,
        'Q29A': lambda a, b: 2 if a and b else 0,
        'Q32A': lambda a, b: -0.5 if a and b else 0,
        'Q34A': lambda a, b: -0.5 if a and b else 0,
        'Q43A': lambda a, b: 0.5 if a and b else 0,
        'Q51A': lambda a, b: 0.5 if a and b else 0,
        'Q56A': lambda a, b: 0.5 if a and b else 0,
        'Q59A': lambda a, b: 0.5 if a and b else 0,
        'Q75A': lambda a, b: 0.5 if a and b else 0,
    },
    'Q10A': {
        'Q34A': lambda a, b: 0.5 if a and b else 0,
        'Q51A': lambda a, b: 0.5 if a and b else 0,
        'Q10A': lambda a, b: 0.5 if a and b else 0,
        'Q15A': lambda a, b: 0.5 if a and b else 0,
        'Q19A': lambda a, b: 0.5 if a and b else 0,
        'Q20A': lambda a, b: 0.5 if a and b else 0,
        'Q36A': lambda a, b: 2 if a and b else 0,
        'Q37A': lambda a, b: 0.5 if a and b else 0,
        'Q44A': lambda a, b: 0.5 if a and b else 0,
        'Q45A': lambda a, b: 0.5 if a and b else 0,
        'Q47A': lambda a, b: 0.5 if a and b else 0,
        'Q40A': lambda a, b: 2 if a and b else 0,
        'Q24A': lambda a, b: -0.5 if a and b else 0,
        'Q63A': lambda a, b: -2 if a and b else 0,
        'Q76A': lambda a, b: -2 if a and b else 0,
        'Q44B': lambda a, b: -2 if a and b else 0,
        'Q47B': lambda a, b: -2 if a and b else 0,
        'Q3A': lambda a, b: -2 if a and b else 0,
        'Q1A': lambda a, b: -0.5 if a and b else 0,
        'Q4A': lambda a, b: -0.5 if a and b else 0,
        'Q46A': lambda a, b: -0.5 if a and b else 0,
        'Q58A': lambda a, b: 0.5 if a and b else 0,
        'Q56A': lambda a, b: 0.5 if a and b else 0,
        'Q60A': lambda a, b: 0.5 if a and b else 0,
        'Q64A': lambda a, b: 0.5 if a and b else 0,
        'Q68A': lambda a, b: 0.5 if a and b else 0,
        'Q70A': lambda a, b: 2 if a and b else 0,
        'Q73A': lambda a, b: 0.5 if a and b else 0,
        'Q75A': lambda a, b: 2 if a and b else 0,
        'Q78A': lambda a, b: 0.5 if a and b else 0,
        'Q83A': lambda a, b: 0.5 if a and b else 0,
        'Q84A': lambda a, b: 0.5 if a and b else 0,
        'Q87A': lambda a, b: 0.5 if a and b else 0,
    },
    'Q11A': {
        'Q53A': lambda a, b: 2 if a and b else 0,
        'Q52A': lambda a, b: 2 if a and b else 0,
        'Q12A': lambda a, b: -0.5 if a and b else 0,
        'Q11A': lambda a, b: -2 if a and b else 0,
        'Q24A': lambda a, b: 0.5 if a and b else 0,
        'Q19A': lambda a, b: 0.5 if a and b else 0,
        'Q83A': lambda a, b: 0.5 if a and b else 0,
        'Q89A': lambda a, b: 0.5 if a and b else 0,
        'Q9A': lambda a, b: 0.5 if a and b else 0,
    },
    'Q12A': {
        'Q53A': lambda a, b: 2 if a and b else 0,
        'Q52A': lambda a, b: 2 if a and b else 0,
        'Q13A': lambda a, b: -2 if a and b else 0,
        'Q11A': lambda a, b: -1.5 if a and b else 0,
        'Q12A': lambda a, b: -2 if a and b else 0,
        'Q24A': lambda a, b: 1.5 if a and b else 0,
        'Q83A': lambda a, b: -2 if a and b else 0,
        'Q86B': lambda a, b: 2 if a and b else 0,
        'Q88A': lambda a, b: 2 if a and b else 0,
    },
    'Q13A': {
        'Q13A': lambda a, b: -2 if a and b else 0,
        'Q12A': lambda a, b: -2 if a and b else 0,
        'Q52A': lambda a, b: -2 if a and b else 0,
        'Q53A': lambda a, b: -2 if a and b else 0,
    },
    'Q14A': {
        'Q88A': lambda a, b: 2 if a and b else 0,
        'Q79A': lambda a, b: 0.5 if a and b else 0,
        'Q78A': lambda a, b: 0.5 if a and b else 0,
        'Q7A': lambda a, b: 2 if a and b else 0,
        'Q16A': lambda a, b: -2 if a and b else 0,
        'Q15A': lambda a, b: -0.5 if a and b else 0,
        'Q14A': lambda a, b: -2 if a and b else 0,
        'Q3A': lambda a, b: -0.5 if a and b else 0,
    },
    'Q15A': {
        'Q16A': lambda a, b: -0.5 if a and b else 0,
        'Q10A': lambda a, b: 0.5 if a and b else 0,
        'Q14A': lambda a, b: -0.5 if a and b else 0,
        'Q15A': lambda a, b: -2 if a and b else 0,
        'Q88A': lambda a, b: 0.5 if a and b else 0,
        'Q79A': lambda a, b: 0.5 if a and b else 0,
        'Q78A': lambda a, b: 0.5 if a and b else 0,
        'Q87A': lambda a, b: -0.5 if a and b else 0,
        'Q82A': lambda a, b: -2 if a and b else 0,
        'Q9A': lambda a, b: -2 if a and b else 0,
    },
    'Q16A': {
        'Q18A': lambda a, b: -2 if a and b else 0,
        'Q16A': lambda a, b: -2 if a and b else 0,
        'Q14A': lambda a, b: -2 if a and b else 0,
        'Q15A': lambda a, b: -0.5 if a and b else 0,
        'Q7A': lambda a, b: 2 if a and b else 0,
        'Q88A': lambda a, b: 2 if a and b else 0,
        'Q79A': lambda a, b: 0.5 if a and b else 0,
        'Q78A': lambda a, b: 0.5 if a and b else 0,
    },
    'Q17A': {
        'Q58A': lambda a, b: 0.5 if a and b else 0,
        'Q34A': lambda a, b: 0.5 if a and b else 0,
        'Q33A': lambda a, b: 0.5 if a and b else 0,
        'Q64A': lambda a, b: 0.5 if a and b else 0,
        'Q78A': lambda a, b: 0.5 if a and b else 0,
        'Q40A': lambda a, b: -0.5 if a and b else 0,
        'Q4A': lambda a, b: -0.5 if a and b else 0,
        'Q3A': lambda a, b: -0.5 if a and b else 0,
        'Q63A': lambda a, b: -2 if a and b else 0,
        'Q44A': lambda a, b: -2 if a and b else 0,
        'Q17A': lambda a, b: -2 if a and b else 0,
    },
    'Q18A': {
        'Q76A': lambda a, b: -0.5 if a and b else 0,
        'Q79B': lambda a, b: -0.5 if a and b else 0,
        'Q87A': lambda a, b: -0.5 if a and b else 0,
        'Q2A': lambda a, b: -0.5 if a and b else 0,
        'Q3A': lambda a, b: -0.5 if a and b else 0,
        'Q7A': lambda a, b: 0.5 if a and b else 0,
        'Q16A': lambda a, b: -2 if a and b else 0,
        'Q18A': lambda a, b: -2 if a and b else 0,
        'Q49A': lambda a, b: 0.5 if a and b else 0,
        'Q58A': lambda a, b: -0.5 if a and b else 0,
        'Q71A': lambda a, b: -0.5 if a and b else 0,
    },
    'Q19A': {
        'Q58A': lambda a, b: 0.5 if a and b else 0,
        'Q10A': lambda a, b: 0.5 if a and b else 0,
        'Q87A': lambda a, b: 0.5 if a and b else 0,
        'Q34A': lambda a, b: 0.5 if a and b else 0,
        'Q11A': lambda a, b: 0.5 if a and b else 0,
        'Q64A': lambda a, b: 0.5 if a and b else 0,
        'Q75A': lambda a, b: 2 if a and b else 0,
        'Q79A': lambda a, b: 0.5 if a and b else 0,
        'Q86B': lambda a, b: 2 if a and b else 0,
        'Q20A': lambda a, b: -0.5 if a and b else 0,
        'Q19A': lambda a, b: -2 if a and b else 0,
        'Q3A': lambda a, b: -0.5 if a and b else 0,
    },
    'Q20A': {
        'Q58A': lambda a, b: 0.5 if a and b else 0,
        'Q79A': lambda a, b: 0.5 if a and b else 0,
        'Q86B': lambda a, b: 0.5 if a and b else 0,
        'Q75A': lambda a, b: 0.5 if a and b else 0,
        'Q64A': lambda a, b: 0.5 if a and b else 0,
        'Q63A': lambda a, b: -0.5 if a and b else 0,
        'Q34A': lambda a, b: 0.5 if a and b else 0,
        'Q20A': lambda a, b: -0.5 if a and b else 0,
        'Q19A': lambda a, b: -0.5 if a and b else 0,
        'Q10A': lambda a, b: 0.5 if a and b else 0,
        'Q3A': lambda a, b: -0.5 if a and b else 0,
    },
    'Q21A': {
        'Q56A': lambda a, b: 0.5 if a and b else 0,
        'Q35A': lambda a, b: -0.5 if a and b else 0,
        'Q21A': lambda a, b: -0.5 if a and b else 0,
        'Q71A': lambda a, b: -0.5 if a and b else 0,
        'Q57A': lambda a, b: -0.5 if a and b else 0,
        'Q78B': lambda a, b: -2 if a and b else 0,
        'Q30A': lambda a, b: 0.5 if a and b else 0,
        'Q88A': lambda a, b: 0.5 if a and b else 0,
    },
    'Q22A': {
        'Q23A': lambda a, b : 0.5 if str(b) in a else 0,
    },
    'Q23A': {
        'Q22A': lambda a, b : 0.5 if str(a) in b else 0,
    },
    'Q24A': {
        'Q24A': lambda a, b : -2 if a and b else 0,
        'Q43A': lambda a, b : -2 if a and b else 0,
        'Q25A': lambda a, b : 2 if a and b else 0,
        'Q12A': lambda a, b : 1 if a and b else 0,
        'Q11A': lambda a, b : 1 if a and b else 0,
        'Q9A': lambda a, b : -1 if a and b else 0,
    },
    'Q25A': {
        'Q25A': lambda a, b : -2 if a and b else 0,
        'Q24A': lambda a, b : 2 if a and b else 0,
        'Q9A': lambda a, b : 2 if a and b else 0,
    },
    'Q26A': {
        'Q4A': lambda a, b : 2 if len(a)!=0 and b else 0,
        'Q26A': lambda a, b : -.5 if any(i == item for item in a for i in b) else (0 if len(a)==len(b)==0 else 9999),
    },
    'Q27A': {
        'Q46A': lambda a, b : 1.5 if len(a)!=0 and b else 0,
        'Q36A': lambda a, b : 1.5 if len(a)!=0 and b else 0,
        'Q75A': lambda a, b : 1.5 if len(a)!=0 and b else 0,
        'Q27A': lambda a, b : 1.5 if any(i == item for item in a for i in b) else (0 if len(a)==len(b)==0 else 9999),
    },
    'Q28A': {
        'Q46A': lambda a, b : 1.5 if a and b else 0,
        'Q75A': lambda a, b : 1.5 if a and b else 0,
        'Q36A': lambda a, b : 1.5 if a and b else 0,
        'Q28A': lambda a, b : 1.5 if any(i == item for item in a for i in b) else (0 if len(a)==len(b)==0 else 9999),
    },
    'Q29A': {
        'Q73A': lambda a, b: 0.5 if a and b else 0,
        'Q58A': lambda a, b: 0.5 if a and b else 0,
        'Q51A': lambda a, b: 0.5 if a and b else 0,
        'Q34A': lambda a, b: 0.5 if a and b else 0,
        'Q9A': lambda a, b: 2 if a and b else 0,
        'Q63A': lambda a, b: -2 if a and b else 0,
        'Q39A': lambda a, b: -2 if a and b else 0,
        'Q46A': lambda a, b: -0.5 if a and b else 0,
        'Q10A': lambda a, b: -0.5 if a and b else 0,
        'Q4A': lambda a, b: -0.5 if a and b else 0,
        'Q2A': lambda a, b: -0.5 if a and b else 0,
    },
    'Q30A': {
        'Q87A': lambda a, b: 0.5 if a and b else 0,
        'Q5A': lambda a, b: -0.5 if a and b else 0,
        'Q30A': lambda a, b: -0.5 if a and b else 0,
        'Q31A': lambda a, b: -0.5 if a and b else 0,
        'Q32A': lambda a, b: -0.5 if a and b else 0,
        'Q35A': lambda a, b: 0.5 if a and b else 0,
        'Q71A': lambda a, b: 0.5 if a and b else 0,
        'Q21A': lambda a, b: 0.5 if a and b else 0,
        'Q51A': lambda a, b: 0.5 if a and b else 0,
        'Q34A': lambda a, b: 2 if a and b else 0,
        'Q78B': lambda a, b: 2 if a and b else 0,
        'Q73A': lambda a, b: 2 if a and b else 0,
        'Q70A': lambda a, b: 2 if a and b else 0,
        'Q72A': lambda a, b: 2 if a and b else 0,
        'Q58A': lambda a, b: 2 if a and b else 0,
        'Q46B': lambda a, b: 2 if a and b else 0,
        'Q57A': lambda a, b: 2 if a and b else 0,
        'Q68A': lambda a, b: 0.5 if a and b else 0,
        'Q36A': lambda a, b: -0.5 if a and b else 0,
        'Q56A': lambda a, b: -0.5 if a and b else 0,
        'Q64A': lambda a, b: 2 if a and b else 0,
        'Q60A': lambda a, b: 0.5 if a and b else 0,
    },
    'Q31A': {
        'Q87A': lambda a, b: 2 if a and b else 0,
        'Q86A': lambda a, b: 0.5 if a and b else 0,
        'Q86B': lambda a, b: 0.5 if a and b else 0,
        'Q82A': lambda a, b: 0.5 if a and b else 0,
        'Q71A': lambda a, b: 2 if a and b else 0,
        'Q72A': lambda a, b: 2 if a and b else 0,
        'Q46B': lambda a, b: 2 if a and b else 0,
        'Q34A': lambda a, b: 2 if a and b else 0,
        'Q57A': lambda a, b: 2 if a and b else 0,
        'Q73A': lambda a, b: 2 if a and b else 0,
        'Q64A': lambda a, b: 2 if a and b else 0,
        'Q70A': lambda a, b: 2 if a and b else 0,
        'Q68A': lambda a, b: 0.5 if a and b else 0,
        'Q74A': lambda a, b: 0.5 if a and b else 0,
        'Q67A': lambda a, b: 0.5 if a and b else 0,
        'Q58A': lambda a, b: 2 if a and b else 0,
        'Q51A': lambda a, b: 0.5 if a and b else 0,
        'Q56A': lambda a, b: 0.5 if a and b else 0,
        'Q65A': lambda a, b: 0.5 if a and b else 0,
        'Q46A': lambda a, b: -0.5 if a and b else 0,
        'Q36A': lambda a, b: -0.5 if a and b else 0,
        'Q30A': lambda a, b: -0.5 if a and b else 0,
        'Q66A': lambda a, b: 2 if a and b else 0,
    },
    'Q32A': {
        'Q51A': lambda a, b: -2 if a and b else 0,
        'Q71A': lambda a, b: -2 if a and b else 0,
        'Q32A': lambda a, b: -2 if a and b else 0,
        'Q2A': lambda a, b: -0.5 if a and b else 0,
        'Q36A': lambda a, b: -0.5 if a and b else 0,
        'Q9A': lambda a, b: -0.5 if a and b else 0,
        'Q30A': lambda a, b: -0.5 if a and b else 0,
        'Q64A': lambda a, b: -0.5 if a and b else 0,
        'Q34A': lambda a, b: -0.5 if a and b else 0,
        'Q79B': lambda a, b: -0.5 if a and b else 0,
        'Q35A': lambda a, b: 2 if a and b else 0,
        'Q63A': lambda a, b: 0.5 if a and b else 0,
        'Q1A': lambda a, b: 2 if a and b else 0,
    },
    'Q33A': {
        'Q87A': lambda a, b: 0.5 if a and b else 0,
        'Q83A': lambda a, b: 0.5 if a and b else 0,
        'Q81A': lambda a, b: 0.5 if a and b else 0,
        'Q86A': lambda a, b: 0.5 if a and b else 0,
        'Q85A': lambda a, b: 2 if a and b else 0,
        'Q34A': lambda a, b: -0.5 if a and b else 0,
        'Q77A': lambda a, b: -0.5 if a and b else 0,
        'Q65A': lambda a, b: -0.5 if a and b else 0,
        'Q33A': lambda a, b: -0.5 if a and b else 0,
        'Q76A': lambda a, b: -0.5 if a and b else 0,
        'Q78B': lambda a, b: 2 if a and b else 0,
        'Q63A': lambda a, b: 2 if a and b else 0,
        'Q72A': lambda a, b: 0.5 if a and b else 0,
        'Q75A': lambda a, b: 0.5 if a and b else 0,
        'Q66A': lambda a, b: 0.5 if a and b else 0,
        'Q46A': lambda a, b: 0.5 if a and b else 0,
        'Q45A': lambda a, b: 0.5 if a and b else 0,
        'Q44A': lambda a, b: 0.5 if a and b else 0,
        'Q61A': lambda a, b: 0.5 if a and b else 0,
        'Q17A': lambda a, b: 0.5 if a and b else 0,
        'Q2A': lambda a, b: 2 if a and b else 0,
        'Q1A': lambda a, b: 0.5 if a and b else 0,
    },
    'Q34A': {
        'Q87A': lambda a, b: -1 if a and b else 0,
        'Q82A': lambda a, b: 1 if a and b else 0,
        'Q20A': lambda a, b: 1 if a and b else 0,
        'Q40A': lambda a, b: 1 if a and b else 0,
        'Q39A': lambda a, b: 2 if a and b else 0,
        'Q62A': lambda a, b: 1 if a and b else 0,
        'Q73A': lambda a, b: -1 if a and b else 0,
        'Q72A': lambda a, b: -1 if a and b else 0,
        'Q71A': lambda a, b: -2 if a and b else 0,
        'Q34A': lambda a, b: -2 if a and b else 0,
        'Q32A': lambda a, b: -1 if a and b else 0,
        'Q33A': lambda a, b: -1 if a and b else 0,
        'Q70A': lambda a, b: -1 if a and b else 0,
        'Q68A': lambda a, b: -1 if a and b else 0,
        'Q38A': lambda a, b: -1 if a and b else 0,
        'Q57A': lambda a, b: -1 if a and b else 0,
        'Q58A': lambda a, b: -2 if a and b else 0,
        'Q64A': lambda a, b: -1 if a and b else 0,
        'Q46B': lambda a, b: -2 if a and b else 0,
        'Q60A': lambda a, b: 1 if a and b else 0,
        'Q77A': lambda a, b: 1 if a and b else 0,
        'Q47A': lambda a, b: 1 if a and b else 0,
        'Q56A': lambda a, b: 2 if a and b else 0,
        'Q65A': lambda a, b: 1 if a and b else 0,
        'Q61A': lambda a, b: 2 if a and b else 0,
        'Q74A': lambda a, b: 2 if a and b else 0,
        'Q46A': lambda a, b: 2 if a and b else 0,
        'Q36A': lambda a, b: 2 if a and b else 0,
        'Q37A': lambda a, b: 1 if a and b else 0,
        'Q54A': lambda a, b: 1 if a and b else 0,
        'Q55A': lambda a, b: 1 if a and b else 0,
        'Q51A': lambda a, b: 1 if a and b else 0,
        'Q31A': lambda a, b: 2 if a and b else 0,
        'Q19A': lambda a, b: 1 if a and b else 0,
        'Q17A': lambda a, b: 1 if a and b else 0,
        'Q10A': lambda a, b: 1 if a and b else 0,
        'Q9A': lambda a, b: -1 if a and b else 0,
        'Q3A': lambda a, b: -1 if a and b else 0,
        'Q1A': lambda a, b: 2 if a and b else 0,
        'Q30A': lambda a, b: 2 if a and b else 0,
        'Q29A': lambda a, b: 1 if a and b else 0,
        'Q63A': lambda a, b: 2 if a and b else 0,
        'Q4A': lambda a, b: 1 if a and b else 0,
    },
    'Q35A': {
        'Q46A': lambda a, b: 1 if a and b else 0,
        'Q30A': lambda a, b: 1 if a and b else 0,
        'Q5A': lambda a, b: 1 if a and b else 0,
        'Q51A': lambda a, b: 1 if a and b else 0,
        'Q71A': lambda a, b: 1 if a and b else 0,
        'Q79B': lambda a, b: 1 if a and b else 0,
        'Q36A': lambda a, b: 2 if a and b else 0,
        'Q32A': lambda a, b: 2 if a and b else 0,
        'Q35A': lambda a, b: -2 if a and b else 0,
        'Q21A': lambda a, b: -1 if a and b else 0,
        'Q4A': lambda a, b: -1 if a and b else 0,
        'Q1A': lambda a, b: -1 if a and b else 0,
    },
    'Q36A': {
        'Q73A': lambda a, b: 2 if a and b else 0,
        'Q72A': lambda a, b: 2 if a and b else 0,
        'Q71A': lambda a, b: 2 if a and b else 0,
        'Q70A': lambda a, b: 2 if a and b else 0,
        'Q68A': lambda a, b: 2 if a and b else 0,
        'Q53A': lambda a, b: 2 if a and b else 0,
        'Q35A': lambda a, b: 2 if a and b else 0,
        'Q67A': lambda a, b: 1.5 if a and b else 0,
        'Q36A': lambda a, b: 1.5 if a and b else 0,
        'Q87A': lambda a, b: 1.5 if a and b else 0,
        'Q27A': lambda a, b: 1.5 if a and b else 0,
        'Q57A': lambda a, b: 1.5 if a and b else 0,
        'Q58A': lambda a, b: 2 if a and b else 0,
        'Q46A': lambda a, b: -1.5 if a and b else 0,
        'Q5A': lambda a, b: -2 if a and b else 0,
        'Q32A': lambda a, b: -1.5 if a and b else 0,
        'Q31A': lambda a, b: -1.5 if a and b else 0,
        'Q51A': lambda a, b: -1.5 if a and b else 0,
        'Q52A': lambda a, b: 1.5 if a and b else 0,
        'Q56A': lambda a, b: 1.5 if a and b else 0,
        'Q66A': lambda a, b: 1.5 if a and b else 0,
        'Q64A': lambda a, b: 2 if a and b else 0,
        'Q34A': lambda a, b: 2 if a and b else 0,
        'Q46B': lambda a, b: 1.5 if a and b else 0,
        'Q79B': lambda a, b: 2 if a and b else 0,
        'Q77A': lambda a, b: 2 if a and b else 0,
        'Q37A': lambda a, b: 1.5 if a and b else 0,
        'Q28A': lambda a, b: 1.5 if a and b else 0,
        'Q1A': lambda a, b: 1.5 if a and b else 0,
        'Q30A': lambda a, b: -1.5 if a and b else 0,
        'Q10A': lambda a, b: 2 if a and b else 0,
    },
    'Q37A': {
        'Q73A': lambda a, b: 2 if a and b else 0,
        'Q72A': lambda a, b: 0.5 if a and b else 0,
        'Q10A': lambda a, b: 0.5 if a and b else 0,
        'Q71A': lambda a, b: 0.5 if a and b else 0,
        'Q70A': lambda a, b: 2 if a and b else 0,
        'Q68A': lambda a, b: 0.5 if a and b else 0,
        'Q58A': lambda a, b: 2 if a and b else 0,
        'Q56A': lambda a, b: 0.5 if a and b else 0,
        'Q87A': lambda a, b: 0.5 if a and b else 0,
        'Q86B': lambda a, b: 0.5 if a and b else 0,
        'Q60A': lambda a, b: -0.5 if a and b else 0,
        'Q64A': lambda a, b: 2 if a and b else 0,
        'Q61A': lambda a, b: -0.5 if a and b else 0,
        'Q46A': lambda a, b: -0.5 if a and b else 0,
        'Q37A': lambda a, b: -2 if a and b else 0,
        'Q36A': lambda a, b: 0.5 if a and b else 0,
        'Q34A': lambda a, b: 0.5 if a and b else 0,
        'Q5A': lambda a, b: -2 if a and b else 0,
        'Q3A': lambda a, b: -0.5 if a and b else 0,
        'Q1A': lambda a, b: -0.5 if a and b else 0,
    },
    'Q38A': {
        'Q82A': lambda a, b: -2 if a and b else 0,
        'Q41A': lambda a, b: -0.5 if a and b else 0,
        'Q40A': lambda a, b: -2 if a and b else 0,
        'Q62A': lambda a, b: -2 if a and b else 0,
        'Q61A': lambda a, b: -2 if a and b else 0,
        'Q54A': lambda a, b: 2 if a and b else 0,
        'Q71A': lambda a, b: 2 if a and b else 0,
        'Q58A': lambda a, b: 2 if a and b else 0,
        'Q38A': lambda a, b: -2 if a and b else 0,
        'Q39A': lambda a, b: -0.5 if a and b else 0,
        'Q34A': lambda a, b: 0.5 if a and b else 0,
    },
    'Q39A': {
        'Q61A': lambda a, b: -0.5 if a and b else 0,
        'Q41A': lambda a, b: -0.5 if a and b else 0,
        'Q54A': lambda a, b: 2 if a and b else 0,
        'Q34A': lambda a, b: 2 if a and b else 0,
        'Q53A': lambda a, b: 0.5 if a and b else 0,
        'Q63A': lambda a, b: -0.5 if a and b else 0,
        'Q40A': lambda a, b: -0.5 if a and b else 0,
        'Q38A': lambda a, b: -0.5 if a and b else 0,
        'Q1A': lambda a, b: -0.5 if a and b else 0,
        'Q39A': lambda a, b: -2 if a and b else 0,
        'Q29A': lambda a, b: -2 if a and b else 0,
    },
    'Q40A': {
        'Q77A': lambda a, b: -2 if a and b else 0,
        'Q41A': lambda a, b: -2 if a and b else 0,
        'Q40A': lambda a, b: -2 if a and b else 0,
        'Q71A': lambda a, b: 2 if a and b else 0,
        'Q89A': lambda a, b: 1 if a and b else 0,
        'Q74A': lambda a, b: 1 if a and b else 0,
        'Q10A': lambda a, b: 2 if a and b else 0,
        'Q66A': lambda a, b: 1 if a and b else 0,
        'Q65A': lambda a, b: 1 if a and b else 0,
        'Q52A': lambda a, b: 2 if a and b else 0,
        'Q53A': lambda a, b: 1 if a and b else 0,
        'Q63A': lambda a, b: -1 if a and b else 0,
        'Q17A': lambda a, b: -1 if a and b else 0,
        'Q39A': lambda a, b: -1 if a and b else 0,
        'Q38A': lambda a, b: -2 if a and b else 0,
        'Q54A': lambda a, b: 2 if a and b else 0,
        'Q34A': lambda a, b: 1 if a and b else 0,
        'Q80A': lambda a, b: -2 if a and b else 0,
        'Q62A': lambda a, b: -2 if a and b else 0,
        'Q61A': lambda a, b: -2 if a and b else 0,
    },
    'Q41A': {
        'Q77A': lambda a, b: -2 if a and b else 0,
        'Q39A': lambda a, b: -1 if a and b else 0,
        'Q38A': lambda a, b: -1 if a and b else 0,
        'Q57A': lambda a, b: 1 if a and b else 0,
        'Q55A': lambda a, b: 1 if a and b else 0,
        'Q52A': lambda a, b: 2 if a and b else 0,
        'Q58A': lambda a, b: 1 if a and b else 0,
        'Q89A': lambda a, b: 2 if a and b else 0,
        'Q74A': lambda a, b: 2 if a and b else 0,
        'Q53A': lambda a, b: 2 if a and b else 0,
        'Q61A': lambda a, b: -2 if a and b else 0,
        'Q62A': lambda a, b: -2 if a and b else 0,
        'Q80A': lambda a, b: -2 if a and b else 0,
        'Q41A': lambda a, b: -2 if a and b else 0,
        'Q40A': lambda a, b: -2 if a and b else 0,
    },
    'Q42A': {
        'Q84A': lambda a, b: -1 if a and b else 0,
        'Q65A': lambda a, b: -2 if a and b else 0,
        'Q42A': lambda a, b: -2 if a and b else 0,
        'Q61A': lambda a, b: 1 if a and b else 0,
        'Q48A': lambda a, b: 1 if a and b else 0,
        'Q78B': lambda a, b: 2 if a and b else 0,
        'Q42B': lambda a, b: 2 if a and b else 0,
        'Q50A': lambda a, b: 2 if a and b else 0,
    },
    'Q42B': {
        'Q65A': lambda a, b: 2 if a and b else 0,
        'Q42A': lambda a, b: 2 if a and b else 0,
    },
    'Q43A': {
        'Q24A': lambda a, b: -2 if a and b else 0,
        'Q43A': lambda a, b: -2 if a and b else 0,
        'Q9A': lambda a, b: 1.5 if a and b else 0,
    },
    'Q44A': {
        'Q44B': lambda a, b: 0.5 if a and b else 0,
        'Q10A': lambda a, b: 0.5 if a and b else 0,
        'Q33A': lambda a, b: 0.5 if a and b else 0,
        'Q44A': lambda a, b: -2 if a and b else 0,
        'Q17A': lambda a, b: -2 if a and b else 0,
    },
    'Q44B': {
        'Q44A': lambda a, b: 0.5 if a and b else 0,
        'Q44B': lambda a, b: -2 if a and b else 0,
    },
    'Q45A': {
        'Q72A': lambda a, b: 0.5 if a and b else 0,
        'Q47A': lambda a, b: -0.5 if a and b else 0,
        'Q47B': lambda a, b: -0.5 if a and b else 0,
        'Q86B': lambda a, b: 0.5 if a and b else 0,
        'Q73A': lambda a, b: 0.5 if a and b else 0,
        'Q33A': lambda a, b: 0.5 if a and b else 0,
        'Q68A': lambda a, b: 0.5 if a and b else 0,
        'Q78A': lambda a, b: 0.5 if a and b else 0,
        'Q58A': lambda a, b: 0.5 if a and b else 0,
        'Q53A': lambda a, b: 0.5 if a and b else 0,
        'Q46A': lambda a, b: -0.5 if a and b else 0,
        'Q52A': lambda a, b: 0.5 if a and b else 0,
        'Q67A': lambda a, b: 0.5 if a and b else 0,
        'Q66A': lambda a, b: 0.5 if a and b else 0,
        'Q88A': lambda a, b: 0.5 if a and b else 0,
        'Q10A': lambda a, b: 0.5 if a and b else 0,
    },
    'Q46A': {
        'Q6A': lambda a, b: -2 if a and b else 0,
        'Q5A': lambda a, b: -2 if a and b else 0,
        'Q4A': lambda a, b: -2 if a and b else 0,
        'Q3A': lambda a, b: 1.5 if a and b else 0,
        'Q2A': lambda a, b: -2 if a and b else 0,
        'Q72A': lambda a, b: 2 if a and b else 0,
        'Q10A': lambda a, b: -1.5 if a and b else 0,
        'Q68A': lambda a, b: 2 if a and b else 0,
        'Q28A': lambda a, b: 1.5 if a and b else 0,
        'Q58A': lambda a, b: 2 if a and b else 0,
        'Q46B': lambda a, b: 2 if a and b else 0,
        'Q35A': lambda a, b: 1.5 if a and b else 0,
        'Q27A': lambda a, b: 1.5 if a and b else 0,
        'Q46A': lambda a, b: -2 if a and b else 0,
        'Q54A': lambda a, b: -1.5 if a and b else 0,
        'Q63A': lambda a, b: -1.5 if a and b else 0,
        'Q36A': lambda a, b: -1.5 if a and b else 0,
        'Q60A': lambda a, b: -1.5 if a and b else 0,
        'Q56A': lambda a, b: 1.5 if a and b else 0,
        'Q79A': lambda a, b: 1.5 if a and b else 0,
        'Q33A': lambda a, b: 1.5 if a and b else 0,
        'Q73A': lambda a, b: 2 if a and b else 0,
        'Q34A': lambda a, b: 2 if a and b else 0,
        'Q77A': lambda a, b: -1.5 if a and b else 0,
        'Q59A': lambda a, b: 1.5 if a and b else 0,
        'Q64A': lambda a, b: 1.5 if a and b else 0,
        'Q45A': lambda a, b: -1.5 if a and b else 0,
        'Q31A': lambda a, b: -1.5 if a and b else 0,
        'Q29A': lambda a, b: -1.5 if a and b else 0,
        'Q37A': lambda a, b: -1.5 if a and b else 0,
        'Q51A': lambda a, b: -1.5 if a and b else 0,
    },
    'Q46B': {
        'Q58A': lambda a, b: -2 if a and b else 0,
        'Q54A': lambda a, b: -0.5 if a and b else 0,
        'Q34A': lambda a, b: -2 if a and b else 0,
        'Q63A': lambda a, b: -0.5 if a and b else 0,
        'Q79A': lambda a, b: 0.5 if a and b else 0,
        'Q5A': lambda a, b: 0.5 if a and b else 0,
        'Q46A': lambda a, b: 2 if a and b else 0,
        'Q31A': lambda a, b: 2 if a and b else 0,
        'Q55A': lambda a, b: 0.5 if a and b else 0,
        'Q79B': lambda a, b: -2 if a and b else 0,
        'Q73A': lambda a, b: -0.5 if a and b else 0,
        'Q74A': lambda a, b: -0.5 if a and b else 0,
        'Q68A': lambda a, b: -2 if a and b else 0,
        'Q53A': lambda a, b: -0.5 if a and b else 0,
        'Q87A': lambda a, b: -0.5 if a and b else 0,
        'Q86A': lambda a, b: -0.5 if a and b else 0,
        'Q46B': lambda a, b: -2 if a and b else 0,
        'Q71A': lambda a, b: -2 if a and b else 0,
        'Q56A': lambda a, b: 2 if a and b else 0,
        'Q30A': lambda a, b: 2 if a and b else 0,
        'Q36A': lambda a, b: 0.5 if a and b else 0,
    },
    'Q47A': {
        'Q34A': lambda a, b: 0.5 if a and b else 0,
        'Q47B': lambda a, b: 2 if a and b else 0,
        'Q52A': lambda a, b: 0.5 if a and b else 0,
        'Q53A': lambda a, b: 0.5 if a and b else 0,
        'Q68A': lambda a, b: 0.5 if a and b else 0,
        'Q72A': lambda a, b: 0.5 if a and b else 0,
        'Q73A': lambda a, b: 0.5 if a and b else 0,
        'Q86B': lambda a, b: 0.5 if a and b else 0,
        'Q10A.': lambda a, b: 0.5 if a and b else 0,
        'Q47B.': lambda a, b: 0.5 if a and b else 0,
        'Q58A.': lambda a, b: 0.5 if a and b else 0,
        'Q67A.': lambda a, b: 0.5 if a and b else 0,
        'Q86B.': lambda a, b: 0.5 if a and b else 0,
        'Q45A': lambda a, b: -2 if a and b else 0,
        'Q47A': lambda a, b: -2 if a and b else 0,
        'Q76A': lambda a, b: -0.5 if a and b else 0,
    },
    'Q47B': {
        'Q47A': lambda a, b: 2 if a and b else 0,
        'Q78B': lambda a, b: 0.5 if a and b else 0,
        'Q1A.': lambda a, b: 0.5 if a and b else 0,
        'Q55A.': lambda a, b: 0.5 if a and b else 0,
        'Q83A.': lambda a, b: 0.5 if a and b else 0,
        'Q10A': lambda a, b: -2 if a and b else 0,
        'Q45A': lambda a, b: -0.5 if a and b else 0,
        'Q47B': lambda a, b: -2 if a and b else 0,
        'Q52A': lambda a, b: -0.5 if a and b else 0,
        'Q76A': lambda a, b: -0.5 if a and b else 0,
        'Q86B': lambda a, b: -0.5 if a and b else 0,
    },
    'Q48A': {
        'Q59A': lambda a, b: -0.5 if a and b else 0,
        'Q78B': lambda a, b: -0.5 if a and b else 0,
        'Q76A': lambda a, b: -0.5 if a and b else 0,
        'Q48A': lambda a, b: -2 if a and b else 0,
        'Q84A': lambda a, b: 0.5 if a and b else 0,
        'Q42A': lambda a, b: 0.5 if a and b else 0,
        'Q74A': lambda a, b: 0.5 if a and b else 0,
        'Q56A': lambda a, b: 0.5 if a and b else 0,
        'Q83A': lambda a, b: 0.5 if a and b else 0,
        'Q81A': lambda a, b: 0.5 if a and b else 0,
        'Q50A': lambda a, b: 2 if a and b else 0,
    },
    'Q49A': {
        'Q68A': lambda a, b: 0.5 if a and b else 0,
        'Q18A': lambda a, b: 0.5 if a and b else 0,
        'Q73A': lambda a, b: 0.5 if a and b else 0,
        'Q72A': lambda a, b: 0.5 if a and b else 0,
        'Q88A': lambda a, b: 0.5 if a and b else 0,
        'Q79B': lambda a, b: -0.5 if a and b else 0,
        'Q49A': lambda a, b: -0.5 if a and b else 0,
    },
    'Q50A': {
        'Q78B': lambda a, b: 1.5 if a and b else 0,
        'Q79B': lambda a, b: 1.5 if a and b else 0,
        'Q48A': lambda a, b: 2 if a and b else 0,
        'Q84A': lambda a, b: 2 if a and b else 0,
        'Q42A': lambda a, b: 2 if a and b else 0,
        'Q87A': lambda a, b: 1.5 if a and b else 0,
        'Q65A': lambda a, b: 1.5 if a and b else 0,
        'Q58A': lambda a, b: 1.5 if a and b else 0,
        'Q72A': lambda a, b: 2 if a and b else 0,
        'Q56A': lambda a, b: 2 if a and b else 0,
        'Q50A': lambda a, b: 2 if a and b else 0,
        'Q1A': lambda a, b: 2 if a and b else 0,
        'Q86B': lambda a, b: 1.5 if a and b else 0,
        'Q81B': lambda a, b: 1.5 if a and b else 0,
        'Q81A': lambda a, b: 1.5 if a and b else 0,
        'Q4A': lambda a, b: 1.5 if a and b else 0,
    },
    'Q51A': {
        'Q73A': lambda a, b: 2 if a and b else 0,
        'Q68A': lambda a, b: 0.5 if a and b else 0,
        'Q35A': lambda a, b: 0.5 if a and b else 0,
        'Q31A': lambda a, b: 0.5 if a and b else 0,
        'Q29A': lambda a, b: 0.5 if a and b else 0,
        'Q10A': lambda a, b: 0.5 if a and b else 0,
        'Q9A': lambda a, b: 0.5 if a and b else 0,
        'Q30A': lambda a, b: 0.5 if a and b else 0,
        'Q66A': lambda a, b: 0.5 if a and b else 0,
        'Q61A': lambda a, b: 0.5 if a and b else 0,
        'Q72A': lambda a, b: 0.5 if a and b else 0,
        'Q71A': lambda a, b: 0.5 if a and b else 0,
        'Q64A': lambda a, b: 0.5 if a and b else 0,
        'Q34A': lambda a, b: 0.5 if a and b else 0,
        'Q57A': lambda a, b: 0.5 if a and b else 0,
        'Q56A': lambda a, b: 0.5 if a and b else 0,
        'Q87A': lambda a, b: 0.5 if a and b else 0,
        'Q77A': lambda a, b: 0.5 if a and b else 0,
        'Q74A': lambda a, b: 0.5 if a and b else 0,
        'Q86B': lambda a, b: 0.5 if a and b else 0,
        'Q79B': lambda a, b: 0.5 if a and b else 0,
        'Q87B': lambda a, b: -0.5 if a and b else 0,
        'Q51A': lambda a, b: -0.5 if a and b else 0,
        'Q46A': lambda a, b: -0.5 if a and b else 0,
        'Q58A': lambda a, b: 0.5 if a and b else 0,
        'Q32A': lambda a, b: -2 if a and b else 0,
    },
    'Q52A': {
        'Q53A': lambda a, b: -2 if a and b else 0,
        'Q13A': lambda a, b: -2 if a and b else 0,
        'Q52A': lambda a, b: -2 if a and b else 0,
        'Q78B': lambda a, b: -0.5 if a and b else 0,
        'Q47B': lambda a, b: -0.5 if a and b else 0,
        'Q68A': lambda a, b: -0.5 if a and b else 0,
        'Q86B': lambda a, b: 0.5 if a and b else 0,
        'Q83A': lambda a, b: 0.5 if a and b else 0,
        'Q47A': lambda a, b: 0.5 if a and b else 0,
        'Q62A': lambda a, b: 0.5 if a and b else 0,
        'Q81A': lambda a, b: 0.5 if a and b else 0,
        'Q80A': lambda a, b: 0.5 if a and b else 0,
        'Q79A': lambda a, b: 0.5 if a and b else 0,
        'Q69A': lambda a, b: 0.5 if a and b else 0,
        'Q61A': lambda a, b: 0.5 if a and b else 0,
        'Q74A': lambda a, b: 0.5 if a and b else 0,
        'Q45A': lambda a, b: 0.5 if a and b else 0,
        'Q41A': lambda a, b: 2 if a and b else 0,
        'Q36A': lambda a, b: 0.5 if a and b else 0,
        'Q78A': lambda a, b: 0.5 if a and b else 0,
        'Q40A': lambda a, b: 2 if a and b else 0,
        'Q79B': lambda a, b: 0.5 if a and b else 0,
        'Q11A': lambda a, b: 2 if a and b else 0,
        'Q12A': lambda a, b: 2 if a and b else 0,
    },
    'Q53A': {
        'Q88A': lambda a, b: 1.5 if a and b else 0,
        'Q83A': lambda a, b: 1.5 if a and b else 0,
        'Q53A': lambda a, b: -2 if a and b else 0,
        'Q13A': lambda a, b: -2 if a and b else 0,
        'Q52A': lambda a, b: -2 if a and b else 0,
        'Q81A': lambda a, b: 1.5 if a and b else 0,
        'Q80A': lambda a, b: 1.5 if a and b else 0,
        'Q79B': lambda a, b: 1.5 if a and b else 0,
        'Q78A': lambda a, b: 1.5 if a and b else 0,
        'Q69A': lambda a, b: 2 if a and b else 0,
        'Q12A': lambda a, b: 2 if a and b else 0,
        'Q11A': lambda a, b: 2 if a and b else 0,
        'Q36A': lambda a, b: 2 if a and b else 0,
        'Q76A': lambda a, b: -2 if a and b else 0,
        'Q68A': lambda a, b: -2 if a and b else 0,
        'Q57A': lambda a, b: -1.5 if a and b else 0,
        'Q46B': lambda a, b: -1.5 if a and b else 0,
        'Q61A': lambda a, b: 2 if a and b else 0,
        'Q62A': lambda a, b: 2 if a and b else 0,
        'Q55A': lambda a, b: 1.5 if a and b else 0,
        'Q45A': lambda a, b: 1.5 if a and b else 0,
        'Q41A': lambda a, b: 2 if a and b else 0,
        'Q40A': lambda a, b: 1.5 if a and b else 0,
        'Q39A': lambda a, b: 1.5 if a and b else 0,
        'Q47A': lambda a, b: 1.5 if a and b else 0,
    },
    'Q54A': {
        'Q86B': lambda a, b: 0.5 if a and b else 0,
        'Q86A': lambda a, b: 0.5 if a and b else 0,
        'Q54A': lambda a, b: -0.5 if a and b else 0,
        'Q46B': lambda a, b: -0.5 if a and b else 0,
        'Q46A': lambda a, b: -0.5 if a and b else 0,
        'Q79B': lambda a, b: 0.5 if a and b else 0,
        'Q72A': lambda a, b: 0.5 if a and b else 0,
        'Q68A': lambda a, b: 0.5 if a and b else 0,
        'Q67A': lambda a, b: 0.5 if a and b else 0,
        'Q87A': lambda a, b: 0.5 if a and b else 0,
        'Q73A': lambda a, b: 0.5 if a and b else 0,
        'Q34A': lambda a, b: 0.5 if a and b else 0,
        'Q78B': lambda a, b: 2 if a and b else 0,
        'Q58A': lambda a, b: 2 if a and b else 0,
        'Q39A': lambda a, b: 2 if a and b else 0,
        'Q38A': lambda a, b: 2 if a and b else 0,
        'Q40A': lambda a, b: 2 if a and b else 0,
    },
    'Q55A': {
        'Q73A': lambda a, b: 2 if a and b else 0,
        'Q72A': lambda a, b: 2 if a and b else 0,
        'Q68A': lambda a, b: 2 if a and b else 0,
        'Q58A': lambda a, b: 2 if a and b else 0,
        'Q87A': lambda a, b: 2 if a and b else 0,
        'Q67A': lambda a, b: 2 if a and b else 0,
        'Q46B': lambda a, b: 0.5 if a and b else 0,
        'Q47B': lambda a, b: 0.5 if a and b else 0,
        'Q70A': lambda a, b: 0.5 if a and b else 0,
        'Q75A': lambda a, b: 0.5 if a and b else 0,
        'Q41A': lambda a, b: 0.5 if a and b else 0,
        'Q66A': lambda a, b: 0.5 if a and b else 0,
        'Q53A': lambda a, b: 0.5 if a and b else 0,
        'Q34A': lambda a, b: 0.5 if a and b else 0,
        'Q79B': lambda a, b: 0.5 if a and b else 0,
        'Q64A': lambda a, b: 0.5 if a and b else 0,
        'Q69A': lambda a, b: 0.5 if a and b else 0,
    },
    'Q56A': {
        'Q78B': lambda a, b: 1 if a and b else 0,
        'Q74A': lambda a, b: 2 if a and b else 0,
        'Q71A': lambda a, b: 2 if a and b else 0,
        'Q46B': lambda a, b: 2 if a and b else 0,
        'Q81A': lambda a, b: 1 if a and b else 0,
        'Q89A': lambda a, b: 1 if a and b else 0,
        'Q9A': lambda a, b: 1 if a and b else 0,
        'Q86A': lambda a, b: 1 if a and b else 0,
        'Q51A': lambda a, b: 1 if a and b else 0,
        'Q10A': lambda a, b: 1 if a and b else 0,
        'Q37A': lambda a, b: 1 if a and b else 0,
        'Q86B': lambda a, b: 1 if a and b else 0,
        'Q79B': lambda a, b: 1 if a and b else 0,
        'Q65A': lambda a, b: -1 if a and b else 0,
        'Q46A': lambda a, b: -1 if a and b else 0,
        'Q46A': lambda a, b: 1 if a and b else 0,
        'Q67A': lambda a, b: 2 if a and b else 0,
        'Q70A': lambda a, b: 2 if a and b else 0,
        'Q73A': lambda a, b: 2 if a and b else 0,
        'Q72A': lambda a, b: 2 if a and b else 0,
        'Q50A': lambda a, b: 2 if a and b else 0,
        'Q87A': lambda a, b: 2 if a and b else 0,
        'Q57A': lambda a, b: 1 if a and b else 0,
        'Q36A': lambda a, b: 1 if a and b else 0,
        'Q34A': lambda a, b: 2 if a and b else 0,
        'Q21A': lambda a, b: 1 if a and b else 0,
        'Q48A': lambda a, b: 1 if a and b else 0,
        'Q68A': lambda a, b: 2 if a and b else 0,
        'Q58A': lambda a, b: 2 if a and b else 0,
        'Q64A': lambda a, b: 2 if a and b else 0,
        'Q66A': lambda a, b: 2 if a and b else 0,
        'Q61A': lambda a, b: -1 if a and b else 0,
        'Q31A': lambda a, b: 1 if a and b else 0,
        'Q4A': lambda a, b: 1 if a and b else 0,
        'Q30A': lambda a, b: -1 if a and b else 0,
        'Q56A': lambda a, b: -1 if a and b else 0,
        'Q5A': lambda a, b: -2 if a and b else 0,
    },
    'Q57A': {
        'Q82A': lambda a, b: 0.5 if a and b else 0,
        'Q62A': lambda a, b: 0.5 if a and b else 0,
        'Q61A': lambda a, b: 2 if a and b else 0,
        'Q51A': lambda a, b: 0.5 if a and b else 0,
        'Q31A': lambda a, b: 2 if a and b else 0,
        'Q41A': lambda a, b: 0.5 if a and b else 0,
        'Q36A': lambda a, b: 0.5 if a and b else 0,
        'Q30A': lambda a, b: 2 if a and b else 0,
        'Q56A': lambda a, b: 0.5 if a and b else 0,
        'Q57A': lambda a, b: -2 if a and b else 0,
        'Q53A': lambda a, b: -0.5 if a and b else 0,
        'Q71A': lambda a, b: -0.5 if a and b else 0,
        'Q21A': lambda a, b: -0.5 if a and b else 0,
        'Q34A': lambda a, b: -0.5 if a and b else 0,
        'Q78B': lambda a, b: -0.5 if a and b else 0,
        'Q84A': lambda a, b: 0.5 if a and b else 0,
        'Q74A': lambda a, b: 0.5 if a and b else 0,
        'Q78A': lambda a, b: 0.5 if a and b else 0,
        'Q79A': lambda a, b: 0.5 if a and b else 0,
    },
    'Q58A': {
        'Q74A': lambda a, b: 2 if a and b else 0,
        'Q38A': lambda a, b: 2 if a and b else 0,
        'Q58A': lambda a, b: -2 if a and b else 0,
        'Q34A': lambda a, b: -2 if a and b else 0,
        'Q46B': lambda a, b: -2 if a and b else 0,
        'Q63A': lambda a, b: 0.5 if a and b else 0,
        'Q51A': lambda a, b: 2 if a and b else 0,
        'Q41A': lambda a, b: 0.5 if a and b else 0,
        'Q46A': lambda a, b: 2 if a and b else 0,
        'Q36A': lambda a, b: 2 if a and b else 0,
        'Q45A': lambda a, b: 0.5 if a and b else 0,
        'Q47A': lambda a, b: 0.5 if a and b else 0,
        'Q37A': lambda a, b: 2 if a and b else 0,
        'Q69A': lambda a, b: 2 if a and b else 0,
        'Q70A': lambda a, b: -0.5 if a and b else 0,
        'Q64A': lambda a, b: -2 if a and b else 0,
        'Q68A': lambda a, b: -2 if a and b else 0,
        'Q81A': lambda a, b: 0.5 if a and b else 0,
        'Q77A': lambda a, b: 0.5 if a and b else 0,
        'Q50A': lambda a, b: 0.5 if a and b else 0,
        'Q73A': lambda a, b: -0.5 if a and b else 0,
        'Q72A': lambda a, b: 0.5 if a and b else 0,
        'Q62A': lambda a, b: 2 if a and b else 0,
        'Q54A': lambda a, b: 2 if a and b else 0,
        'Q55A': lambda a, b: 2 if a and b else 0,
        'Q56A': lambda a, b: 2 if a and b else 0,
        'Q60A': lambda a, b: 2 if a and b else 0,
        'Q30A': lambda a, b: 2 if a and b else 0,
        'Q10A': lambda a, b: 2 if a and b else 0,
        'Q61A': lambda a, b: 0.5 if a and b else 0,
        'Q31A': lambda a, b: 2 if a and b else 0,
        'Q20A': lambda a, b: 0.5 if a and b else 0,
        'Q88A': lambda a, b: 0.5 if a and b else 0,
        'Q79A': lambda a, b: 0.5 if a and b else 0,
        'Q19A': lambda a, b: 0.5 if a and b else 0,
        'Q17A': lambda a, b: 0.5 if a and b else 0,
        'Q29A': lambda a, b: 0.5 if a and b else 0,
        'Q78B': lambda a, b: -0.5 if a and b else 0,
        'Q76A': lambda a, b: -2 if a and b else 0,
        'Q5A': lambda a, b: 2 if a and b else 0,
        'Q4A': lambda a, b: 0.5 if a and b else 0,
        'Q1A': lambda a, b: 0.5 if a and b else 0,
        'Q18A': lambda a, b: -0.5 if a and b else 0,
        'Q3A': lambda a, b: -0.5 if a and b else 0,
        'Q2A': lambda a, b: -0.5 if a and b else 0,
    },
    'Q59A': {
        'Q59A': lambda a, b: -2 if a and b else 0,
        'Q60A': lambda a, b: 2 if a and b else 0,
        'Q46A': lambda a, b: 0.5 if a and b else 0,
        'Q9A': lambda a, b: 0.5 if a and b else 0,
        'Q48A': lambda a, b: -0.5 if a and b else 0,
        'Q3A': lambda a, b: -0.5 if a and b else 0,
        'Q1A': lambda a, b: -0.5 if a and b else 0,
    },
    'Q60A': {
        'Q79B': lambda a, b: 1 if a and b else 0,
        'Q73A': lambda a, b: 2 if a and b else 0,
        'Q70A': lambda a, b: 2 if a and b else 0,
        'Q78A': lambda a, b: 1 if a and b else 0,
        'Q74A': lambda a, b: 1 if a and b else 0,
        'Q68A': lambda a, b: 1 if a and b else 0,
        'Q64A': lambda a, b: 2 if a and b else 0,
        'Q72A': lambda a, b: 1 if a and b else 0,
        'Q30A': lambda a, b: 1 if a and b else 0,
        'Q87A': lambda a, b: 2 if a and b else 0,
        'Q86A': lambda a, b: 1 if a and b else 0,
        'Q79A': lambda a, b: 2 if a and b else 0,
        'Q77A': lambda a, b: -1 if a and b else 0,
        'Q58A': lambda a, b: 2 if a and b else 0,
        'Q37A': lambda a, b: -1 if a and b else 0,
        'Q34A': lambda a, b: 1 if a and b else 0,
        'Q10A': lambda a, b: 1 if a and b else 0,
        'Q59A': lambda a, b: 2 if a and b else 0,
        'Q61A': lambda a, b: -2 if a and b else 0,
        'Q46A': lambda a, b: -1 if a and b else 0,
    },
    'Q61A': {
        'Q77A': lambda a, b: -1 if a and b else 0,
        'Q62A': lambda a, b: -2 if a and b else 0,
        'Q60A': lambda a, b: -2 if a and b else 0,
        'Q61A': lambda a, b: -2 if a and b else 0,
        'Q65A': lambda a, b: 2 if a and b else 0,
        'Q53A': lambda a, b: 2 if a and b else 0,
        'Q58A': lambda a, b: 1 if a and b else 0,
        'Q52A': lambda a, b: 1 if a and b else 0,
        'Q51A': lambda a, b: 1 if a and b else 0,
        'Q66A': lambda a, b: 1 if a and b else 0,
        'Q87A': lambda a, b: 2 if a and b else 0,
        'Q89A': lambda a, b: 2 if a and b else 0,
        'Q88A': lambda a, b: 1 if a and b else 0,
        'Q81A': lambda a, b: 2 if a and b else 0,
        'Q81B': lambda a, b: 2 if a and b else 0,
        'Q80A': lambda a, b: -2 if a and b else 0,
        'Q78B': lambda a, b: -1 if a and b else 0,
        'Q74A': lambda a, b: 2 if a and b else 0,
        'Q71A': lambda a, b: 1 if a and b else 0,
        'Q57A': lambda a, b: 2 if a and b else 0,
        'Q56A': lambda a, b: -1 if a and b else 0,
        'Q42A': lambda a, b: 1 if a and b else 0,
        'Q41A': lambda a, b: -2 if a and b else 0,
        'Q40A': lambda a, b: -2 if a and b else 0,
        'Q39A': lambda a, b: -1 if a and b else 0,
        'Q38A': lambda a, b: -2 if a and b else 0,
        'Q37A': lambda a, b: -1 if a and b else 0,
        'Q34A': lambda a, b: 2 if a and b else 0,
        'Q33A': lambda a, b: 1 if a and b else 0,
    },
    'Q62A': {
        'Q82A': lambda a, b: -2 if a and b else 0,
        'Q77A': lambda a, b: -1 if a and b else 0,
        'Q62A': lambda a, b: -2 if a and b else 0,
        'Q38A': lambda a, b: -2 if a and b else 0,
        'Q40A': lambda a, b: -2 if a and b else 0,
        'Q61A': lambda a, b: -2 if a and b else 0,
        'Q41A': lambda a, b: -2 if a and b else 0,
        'Q63A': lambda a, b: -1 if a and b else 0,
        'Q71A': lambda a, b: 1 if a and b else 0,
        'Q52A': lambda a, b: 1 if a and b else 0,
        'Q58A': lambda a, b: 2 if a and b else 0,
        'Q53A': lambda a, b: 2 if a and b else 0,
        'Q34A': lambda a, b: 1 if a and b else 0,
        'Q74A': lambda a, b: 1 if a and b else 0,
        'Q57A': lambda a, b: 1 if a and b else 0,
        'Q87A': lambda a, b: 1 if a and b else 0,
        'Q66A': lambda a, b: 1 if a and b else 0,
    },
    'Q63A': {
        'Q68A': lambda a, b: 2 if a and b else 0,
        'Q34A': lambda a, b: 2 if a and b else 0,
        'Q1A': lambda a, b: -0.5 if a and b else 0,
        'Q58A': lambda a, b: 0.5 if a and b else 0,
        'Q32A': lambda a, b: 0.5 if a and b else 0,
        'Q29A': lambda a, b: -2 if a and b else 0,
        'Q76A': lambda a, b: -2 if a and b else 0,
        'Q10A': lambda a, b: -2 if a and b else 0,
        'Q74A': lambda a, b: 0.5 if a and b else 0,
        'Q4A': lambda a, b: -0.5 if a and b else 0,
        'Q62A': lambda a, b: -0.5 if a and b else 0,
        'Q20A': lambda a, b: -0.5 if a and b else 0,
        'Q39A': lambda a, b: -0.5 if a and b else 0,
        'Q17A': lambda a, b: -0.5 if a and b else 0,
        'Q46A': lambda a, b: -0.5 if a and b else 0,
        'Q40A': lambda a, b: -0.5 if a and b else 0,
        'Q2A': lambda a, b: -0.5 if a and b else 0,
        'Q64A': lambda a, b: 0.5 if a and b else 0,
        'Q65A': lambda a, b: 0.5 if a and b else 0,
        'Q33A': lambda a, b: 2 if a and b else 0,
        'Q73A': lambda a, b: 2 if a and b else 0,
    },
    'Q64A': {
        'Q68A': lambda a, b: -2 if a and b else 0,
        'Q58A': lambda a, b: -2 if a and b else 0,
        'Q64A': lambda a, b: -2 if a and b else 0,
        'Q70A': lambda a, b: -0.5 if a and b else 0,
        'Q71A': lambda a, b: -0.5 if a and b else 0,
        'Q73A': lambda a, b: -0.5 if a and b else 0,
        'Q32A': lambda a, b: -0.5 if a and b else 0,
        'Q34A': lambda a, b: -0.5 if a and b else 0,
        'Q3A': lambda a, b: -0.5 if a and b else 0,
        'Q82A': lambda a, b: 0.5 if a and b else 0,
        'Q17A': lambda a, b: 0.5 if a and b else 0,
        'Q55A': lambda a, b: 0.5 if a and b else 0,
        'Q63A': lambda a, b: 0.5 if a and b else 0,
        'Q46A': lambda a, b: 0.5 if a and b else 0,
        'Q56A': lambda a, b: 2 if a and b else 0,
        'Q65A': lambda a, b: -2 if a and b else 0,
        'Q51A': lambda a, b: 0.5 if a and b else 0,
        'Q20A': lambda a, b: 0.5 if a and b else 0,
        'Q19A': lambda a, b: 0.5 if a and b else 0,
        'Q10A': lambda a, b: 0.5 if a and b else 0,
        'Q60A': lambda a, b: 2 if a and b else 0,
        'Q37A': lambda a, b: 2 if a and b else 0,
        'Q36A': lambda a, b: 2 if a and b else 0,
        'Q30A': lambda a, b: 2 if a and b else 0,
        'Q31A': lambda a, b: 2 if a and b else 0,
        'Q5A': lambda a, b: 2 if a and b else 0,
        'Q4A': lambda a, b: 0.5 if a and b else 0,
        'Q1A': lambda a, b: 0.5 if a and b else 0,
        'Q2A': lambda a, b: -2 if a and b else 0,
    },
    'Q65A': {
        'Q84A': lambda a, b: -1 if a and b else 0,
        'Q56A': lambda a, b: -1 if a and b else 0,
        'Q65A': lambda a, b: -2 if a and b else 0,
        'Q78B': lambda a, b: 1 if a and b else 0,
        'Q61A': lambda a, b: 2 if a and b else 0,
        'Q63A': lambda a, b: 1 if a and b else 0,
        'Q34A': lambda a, b: 1 if a and b else 0,
        'Q81A': lambda a, b: -2 if a and b else 0,
        'Q81B': lambda a, b: 1 if not a and b else (-2 if a and b else 0),
        'Q74A': lambda a, b: -2 if a and b else 0,
        'Q33A': lambda a, b: -1 if a and b else 0,
        'Q80A': lambda a, b: 1 if a and b else 0,
        'Q50A': lambda a, b: 1 if a and b else 0,
        'Q31A': lambda a, b: 1 if a and b else 0,
        'Q1A': lambda a, b: 1 if a and b else 0,
        'Q40A': lambda a, b: 1 if a and b else 0,
        'Q64A': lambda a, b: -2 if a and b else 0,
        'Q42A': lambda a, b: -2 if a and b else 0,
        'Q42B': lambda a, b: 2 if a and b else 0,
    },
    'Q66A': {
        'Q83A': lambda a, b: 1 if a and b else 0,
        'Q67A': lambda a, b: 2 if a and b else 0,
        'Q81A': lambda a, b: 1 if a and b else 0,
        'Q51A': lambda a, b: 1 if a and b else 0,
        'Q74A': lambda a, b: 1 if a and b else 0,
        'Q88A': lambda a, b: 1 if a and b else 0,
        'Q84A': lambda a, b: 1 if a and b else 0,
        'Q79A': lambda a, b: 1 if a and b else 0,
        'Q78B': lambda a, b: 1 if a and b else 0,
        'Q77A': lambda a, b: 1 if a and b else 0,
        'Q55A': lambda a, b: 1 if a and b else 0,
        'Q56A': lambda a, b: 2 if a and b else 0,
        'Q76A': lambda a, b: 1 if a and b else 0,
        'Q61A': lambda a, b: 1 if a and b else 0,
        'Q69A': lambda a, b: 1 if a and b else 0,
        'Q45A': lambda a, b: 1 if a and b else 0,
        'Q40A': lambda a, b: 1 if a and b else 0,
        'Q62A': lambda a, b: 1 if a and b else 0,
        'Q66A': lambda a, b: 2 if a and b else 0,
        'Q31A': lambda a, b: 2 if a and b else 0,
        'Q36A': lambda a, b: 1 if a and b else 0,
        'Q33A': lambda a, b: 1 if a and b else 0,
    },
    'Q67A': {
        'Q83A': lambda a, b: 1 if a and b else 0,
        'Q84A': lambda a, b: 1 if a and b else 0,
        'Q66A': lambda a, b: 2 if a and b else 0,
        'Q69A': lambda a, b: 1 if a and b else 0,
        'Q74A': lambda a, b: 1 if a and b else 0,
        'Q75A': lambda a, b: 1 if a and b else 0,
        'Q54A': lambda a, b: 1 if a and b else 0,
        'Q55A': lambda a, b: 2 if a and b else 0,
        'Q88A': lambda a, b: 1 if a and b else 0,
        'Q47A': lambda a, b: 1 if a and b else 0,
        'Q81A': lambda a, b: 1 if a and b else 0,
        'Q81B': lambda a, b: 1 if a and b else 0,
        'Q67A': lambda a, b: 2 if a and b else 0,
        'Q56A': lambda a, b: 2 if a and b else 0,
        'Q45A': lambda a, b: 1 if a and b else 0,
        'Q36A': lambda a, b: 1 if a and b else 0,
        'Q31A': lambda a, b: 1 if a and b else 0,
    },
    'Q68A': {
        'Q69A': lambda a, b: 1.5 if a and b else 0,
        'Q72A': lambda a, b: 1.5 if a and b else 0,
        'Q47A': lambda a, b: 1.5 if a and b else 0,
        'Q51A': lambda a, b: 1.5 if a and b else 0,
        'Q54A': lambda a, b: 1.5 if a and b else 0,
        'Q49A': lambda a, b: 1.5 if a and b else 0,
        'Q45A': lambda a, b: 1.5 if a and b else 0,
        'Q64A': lambda a, b: -2 if a and b else 0,
        'Q34A': lambda a, b: -1.5 if a and b else 0,
        'Q73A': lambda a, b: -2 if a and b else 0,
        'Q68A': lambda a, b: -2 if a and b else 0,
        'Q58A': lambda a, b: -2 if a and b else 0,
        'Q63A': lambda a, b: 2 if a and b else 0,
        'Q36A': lambda a, b: 2 if a and b else 0,
        'Q55A': lambda a, b: 2 if a and b else 0,
        'Q56A': lambda a, b: 2 if a and b else 0,
        'Q46A': lambda a, b: 2 if a and b else 0,
        'Q37A': lambda a, b: 1.5 if a and b else 0,
        'Q30A': lambda a, b: 1.5 if a and b else 0,
        'Q60A': lambda a, b: 1.5 if a and b else 0,
        'Q10A': lambda a, b: 1.5 if a and b else 0,
        'Q31A': lambda a, b: 1.5 if a and b else 0,
        'Q46B': lambda a, b: -2 if a and b else 0,
        'Q52A': lambda a, b: -1.5 if a and b else 0,
        'Q53A': lambda a, b: -2 if a and b else 0,
    },
    'Q69A': {
        'Q68A.': lambda a, b: 0.5 if a and b else 0,
        'Q58A.': lambda a, b: 2 if a and b else 0,
        'Q53A.': lambda a, b: 2 if a and b else 0,
        'Q67A': lambda a, b: 0.5 if a and b else 0,
        'Q73A.': lambda a, b: 0.5 if a and b else 0,
        'Q72A': lambda a, b: 0.5 if a and b else 0,
        'Q86B': lambda a, b: 0.5 if a and b else 0,
        'Q79B': lambda a, b: 0.5 if a and b else 0,
        'Q66A': lambda a, b: 0.5 if a and b else 0,
        'Q55A': lambda a, b: 0.5 if a and b else 0,
        'Q52A': lambda a, b: 0.5 if a and b else 0,
    },
    'Q70A': {
        'Q71A': lambda a, b: -0.5 if a and b else 0,
        'Q70A': lambda a, b: -2 if a and b else 0,
        'Q73A': lambda a, b: -0.5 if a and b else 0,
        'Q34A': lambda a, b: -0.5 if a and b else 0,
        'Q64A': lambda a, b: -0.5 if a and b else 0,
        'Q72A': lambda a, b: -0.5 if a and b else 0,
        'Q87A.': lambda a, b: -0.5 if a and b else 0,
        'Q58A': lambda a, b: -0.5 if a and b else 0,
        'Q56A': lambda a, b: 2 if a and b else 0,
        'Q37A': lambda a, b: 2 if a and b else 0,
        'Q36A': lambda a, b: 2 if a and b else 0,
        'Q30A': lambda a, b: 2 if a and b else 0,
        'Q31A': lambda a, b: 2 if a and b else 0,
        'Q10A': lambda a, b: 2 if a and b else 0,
        'Q60A': lambda a, b: 2 if a and b else 0,
        'Q55A': lambda a, b: 0.5 if a and b else 0,
    },
    'Q71A': {
        'Q82A': lambda a, b: 2 if a and b else 0,
        'Q70A': lambda a, b: -0.5 if a and b else 0,
        'Q71A': lambda a, b: -0.5 if a and b else 0,
        'Q21A': lambda a, b: -0.5 if a and b else 0,
        'Q64A': lambda a, b: -0.5 if a and b else 0,
        'Q57A': lambda a, b: -0.5 if a and b else 0,
        'Q18A': lambda a, b: -0.5 if a and b else 0,
        'Q46B': lambda a, b: -2 if a and b else 0,
        'Q34A': lambda a, b: -2 if a and b else 0,
        'Q32A': lambda a, b: -2 if a and b else 0,
        'Q86A': lambda a, b: 0.5 if a and b else 0,
        'Q51A': lambda a, b: 0.5 if a and b else 0,
        'Q56A': lambda a, b: 2 if a and b else 0,
        'Q36A': lambda a, b: 2 if a and b else 0,
        'Q74A': lambda a, b: 0.5 if a and b else 0,
        'Q79A': lambda a, b: 0.5 if a and b else 0,
        'Q88A': lambda a, b: 0.5 if a and b else 0,
        'Q62A': lambda a, b: 0.5 if a and b else 0,
        'Q40A': lambda a, b: 2 if a and b else 0,
        'Q38A': lambda a, b: 2 if a and b else 0,
        'Q30A': lambda a, b: 0.5 if a and b else 0,
        'Q31A': lambda a, b: 2 if a and b else 0,
        'Q35A': lambda a, b: 0.5 if a and b else 0,
        'Q37A': lambda a, b: 0.5 if a and b else 0,
        'Q61A': lambda a, b: 0.5 if a and b else 0,
    },
    'Q72A': {
        'Q69A': lambda a, b: 1 if a and b else 0,
        'Q51A': lambda a, b: 1 if a and b else 0,
        'Q50A': lambda a, b: 2 if a and b else 0,
        'Q54A': lambda a, b: 1 if a and b else 0,
        'Q70A': lambda a, b: -1 if a and b else 0,
        'Q34A': lambda a, b: -1 if a and b else 0,
        'Q74A': lambda a, b: 2 if a and b else 0,
        'Q72A': lambda a, b: 2 if a and b else 0,
        'Q55A': lambda a, b: 2 if a and b else 0,
        'Q30A': lambda a, b: 2 if a and b else 0,
        'Q31A': lambda a, b: 2 if a and b else 0,
        'Q47A': lambda a, b: 1 if a and b else 0,
        'Q46A': lambda a, b: 2 if a and b else 0,
        'Q49A': lambda a, b: 1 if a and b else 0,
        'Q68A': lambda a, b: 1 if a and b else 0,
        'Q60A': lambda a, b: 2 if a and b else 0,
        'Q79A': lambda a, b: 1 if a and b else 0,
        'Q58A': lambda a, b: 1 if a and b else 0,
        'Q45A': lambda a, b: 1 if a and b else 0,
        'Q33A': lambda a, b: 1 if a and b else 0,
        'Q37A': lambda a, b: 1 if a and b else 0,
        'Q36A': lambda a, b: 2 if a and b else 0,
        'Q73A': lambda a, b: 2 if a and b else 0,
        'Q83A': lambda a, b: 2 if a and b else 0,
        'Q82A': lambda a, b: 2 if a and b else 0,
        'Q56A': lambda a, b: 2 if a and b else 0,
        'Q76A': lambda a, b: -2 if a and b else 0,
    },
    'Q73A': {
        'Q69A': lambda a, b: 1.5 if a and b else 0,
        'Q68A': lambda a, b: -2 if a and b else 0,
        'Q70A': lambda a, b: -1.5 if a and b else 0,
        'Q64A': lambda a, b: -1.5 if a and b else 0,
        'Q60A': lambda a, b: 2 if a and b else 0,
        'Q58A': lambda a, b: -1.5 if a and b else 0,
        'Q46B': lambda a, b: -1.5 if a and b else 0,
        'Q63A': lambda a, b: 2 if a and b else 0,
        'Q83A': lambda a, b: 1.5 if a and b else 0,
        'Q10A': lambda a, b: 1.5 if a and b else 0,
        'Q45A': lambda a, b: 1.5 if a and b else 0,
        'Q72A': lambda a, b: 2 if a and b else 0,
        'Q76A': lambda a, b: -2 if a and b else 0,
        'Q56A': lambda a, b: 2 if a and b else 0,
        'Q55A': lambda a, b: 2 if a and b else 0,
        'Q54A': lambda a, b: 1.5 if a and b else 0,
        'Q51A': lambda a, b: 2 if a and b else 0,
        'Q37A': lambda a, b: 2 if a and b else 0,
        'Q47A': lambda a, b: 1.5 if a and b else 0,
        'Q46A': lambda a, b: 2 if a and b else 0,
        'Q29A': lambda a, b: 1.5 if a and b else 0,
        'Q49A': lambda a, b: 1.5 if a and b else 0,
        'Q34A': lambda a, b: -1.5 if a and b else 0,
        'Q36A': lambda a, b: 2 if a and b else 0,
        'Q31A': lambda a, b: 2 if a and b else 0,
        'Q30A': lambda a, b: 2 if a and b else 0,
        'Q5A': lambda a, b: 2 if a and b else 0,
        'Q1A': lambda a, b: 1.5 if a and b else 0,
    },
    'Q74A': {
        'Q66A': lambda a, b: 1 if a and b else 0,
        'Q40A': lambda a, b: 1 if a and b else 0,
        'Q48A': lambda a, b: 1 if a and b else 0,
        'Q67A': lambda a, b: 1 if a and b else 0,
        'Q62A': lambda a, b: 1 if a and b else 0,
        'Q65A': lambda a, b: -2 if a and b else 0,
        'Q74A': lambda a, b: 1 if a and b else 0,
        'Q58A': lambda a, b: 2 if a and b else 0,
        'Q87A': lambda a, b: 2 if a and b else 0,
        'Q89A': lambda a, b: 1 if a and b else 0,
        'Q79A': lambda a, b: 1 if a and b else 0,
        'Q79B': lambda a, b: 1 if a and b else 0,
        'Q75A': lambda a, b: 1 if a and b else 0,
        'Q72A': lambda a, b: 2 if a and b else 0,
        'Q78B': lambda a, b: 1 if a and b else 0,
        'Q56A': lambda a, b: 2 if a and b else 0,
        'Q57A': lambda a, b: 1 if a and b else 0,
        'Q78A': lambda a, b: 1 if a and b else 0,
        'Q52A': lambda a, b: 1 if a and b else 0,
        'Q71A': lambda a, b: 1 if a and b else 0,
        'Q31A': lambda a, b: 1 if a and b else 0,
        'Q51A': lambda a, b: 1 if a and b else 0,
        'Q81A': lambda a, b: 1 if a and b else 0,
        'Q63A': lambda a, b: 1 if a and b else 0,
        'Q81B': lambda a, b: 2 if a and b else 0,
        'Q60A': lambda a, b: 1 if a and b else 0,
        'Q1A': lambda a, b: 1 if a and b else 0,
        'Q34A': lambda a, b: 2 if a and b else 0,
        'Q41A': lambda a, b: 2 if a and b else 0,
        'Q61A': lambda a, b: 2 if a and b else 0,
        'Q46B': lambda a, b: -1 if a and b else 0,
    },
    'Q75A': {
        'Q75A': lambda a, b: 0.5 if a and b else 0,
        'Q88A': lambda a, b: 0.5 if a and b else 0,
        'Q86B': lambda a, b: 0.5 if a and b else 0,
        'Q85A': lambda a, b: 0.5 if a and b else 0,
        'Q55A': lambda a, b: 0.5 if a and b else 0,
        'Q28A': lambda a, b: 0.5 if a and b else 0,
        'Q80A': lambda a, b: 0.5 if a and b else 0,
        'Q20A': lambda a, b: 0.5 if a and b else 0,
        'Q74A': lambda a, b: 0.5 if a and b else 0,
        'Q78A': lambda a, b: 0.5 if a and b else 0,
        'Q33A': lambda a, b: 0.5 if a and b else 0,
        'Q67A': lambda a, b: 0.5 if a and b else 0,
        'Q9A': lambda a, b: 0.5 if a and b else 0,
        'Q19A': lambda a, b: 2 if a and b else 0,
        'Q10A': lambda a, b: 2 if a and b else 0,
        'Q1A': lambda a, b: 2 if a and b else 0,
        'Q76A': lambda a, b: -2 if a and b else 0,
        'Q27A': lambda a, b: 0.5 if a and b else 0,
        'Q4A': lambda a, b: 0.5 if a and b else 0,
        'Q3A': lambda a, b: -0.5 if a and b else 0,
    },
    'Q76A': {
        'Q77A': lambda a, b: 0.5 if a and b else 0,
        'Q76A': lambda a, b: -2 if a and b else 0,
        'Q33A': lambda a, b: -0.5 if a and b else 0,
        'Q9A': lambda a, b: -2 if a and b else 0,
        'Q89A': lambda a, b: -0.5 if a and b else 0,
        'Q48A': lambda a, b: -0.5 if a and b else 0,
        'Q18A.': lambda a, b: -0.5 if a and b else 0,
        'Q88A': lambda a, b: -0.5 if a and b else 0,
        'Q47B': lambda a, b: -0.5 if a and b else 0,
        'Q72A': lambda a, b: -2 if a and b else 0,
        'Q10A': lambda a, b: -2 if a and b else 0,
        'Q75A': lambda a, b: -2 if a and b else 0,
        'Q86B': lambda a, b: -2 if a and b else 0,
        'Q87B': lambda a, b: -2 if a and b else 0,
        'Q87A': lambda a, b: -2 if a and b else 0,
        'Q85A': lambda a, b: -2 if a and b else 0,
        'Q78A': lambda a, b: 0.5 if a and b else 0,
        'Q73A': lambda a, b: -2 if a and b else 0,
        'Q66A': lambda a, b: -0.5 if a and b else 0,
        'Q47A': lambda a, b: -0.5 if a and b else 0,
        'Q63A': lambda a, b: -0.5 if a and b else 0,
        'Q58A': lambda a, b: -2 if a and b else 0,
        'Q53A': lambda a, b: -2 if a and b else 0,
        'Q4A': lambda a, b: -0.5 if a and b else 0,
    },
    'Q77A': {
        'Q76A': lambda a, b: 0.5 if a and b else 0,
        'Q36A': lambda a, b: 0.5 if a and b else 0,
        'Q89A': lambda a, b: -0.5 if not a and b else 0,
        'Q62A': lambda a, b: -0.5 if a and b else 0,
        'Q61A': lambda a, b: -0.5 if a and b else 0,
        'Q58A': lambda a, b: 0.5 if a and b else 0,
        'Q46A': lambda a, b: -0.5 if a and b else 0,
        'Q33A': lambda a, b: -0.5 if a and b else 0,
        'Q40A': lambda a, b: -2 if a and b else 0,
        'Q41A': lambda a, b: -2 if a and b else 0,
        'Q60A': lambda a, b: -0.5 if a and b else 0,
        'Q66A': lambda a, b: 0.5 if a and b else 0,
        'Q34A': lambda a, b: 0.5 if a and b else 0,
        'Q51A': lambda a, b: 0.5 if a and b else 0,
    },
    'Q78A': {
        'Q10A': lambda a, b: 0.5 if a and b else 0,
        'Q14A': lambda a, b: 0.5 if a and b else 0,
        'Q15A': lambda a, b: 0.5 if a and b else 0,
        'Q16A': lambda a, b: 0.5 if a and b else 0,
        'Q17A': lambda a, b: 0.5 if a and b else 0,
        'Q45A': lambda a, b: 0.5 if a and b else 0,
        'Q52A': lambda a, b: 0.5 if a and b else 0,
        'Q53A': lambda a, b: 0.5 if a and b else 0,
        'Q57A': lambda a, b: 0.5 if a and b else 0,
        'Q60A': lambda a, b: 0.5 if a and b else 0,
        'Q74A': lambda a, b: 0.5 if a and b else 0,
        'Q75A': lambda a, b: 0.5 if a and b else 0,
        'Q78A': lambda a, b: 0.5 if a and b else 0,
        'Q78B': lambda a, b: 0.5 if a and b else 0,
        'Q80A': lambda a, b: 0.5 if a and b else 0,
        'Q83A': lambda a, b: 0.5 if a and b else 0,
        'Q86A': lambda a, b: 0.5 if a and b else 0,
        'Q87A': lambda a, b: 0.5 if a and b else 0,
        'Q87B': lambda a, b: 0.5 if a and b else 0,
        'Q9A': lambda a, b: 2 if a and b else 0,
    },
    'Q78B': {
        'Q76A': lambda a, b: -0.5 if a and b else 0,
        'Q30A': lambda a, b: 2 if a and b else 0,
        'Q33A': lambda a, b: 2 if a and b else 0,
        'Q42A': lambda a, b: 2 if a and b else 0,
        'Q47B': lambda a, b: 0.5 if a and b else 0,
        'Q56A': lambda a, b: 0.5 if a and b else 0,
        'Q65A': lambda a, b: 0.5 if a and b else 0,
        'Q74A': lambda a, b: 0.5 if a and b else 0,
        'Q81A': lambda a, b: 0.5 if a and b else 0,
        'Q81B': lambda a, b: 0.5 if a and b else 0,
        'Q83A': lambda a, b: 0.5 if a and b else 0,
        'Q84A': lambda a, b: 2 if a and b else 0,
        'Q88A': lambda a, b: 0.5 if a and b else 0,
        'Q50A': lambda a, b: 0.5 if a and b else 0,
        'Q54A': lambda a, b: 2 if a and b else 0,
        'Q21A': lambda a, b: -2 if a and b else 0,
        'Q48A': lambda a, b: -0.5 if a and b else 0,
        'Q52A': lambda a, b: -0.5 if a and b else 0,
        'Q57A': lambda a, b: -0.5 if a and b else 0,
        'Q58A': lambda a, b: -0.5 if a and b else 0,
        'Q61A': lambda a, b: -0.5 if a and b else 0,
        'Q66A': lambda a, b: -0.5 if a and b else 0,
        'Q87A': lambda a, b: -2 if a and b else 0,
        'Q9A': lambda a, b: -0.5 if a and b else 0,
    },
    'Q79A': {
        'Q14A': lambda a, b: 0.5 if a and b else 0,
        'Q15A': lambda a, b: 0.5 if a and b else 0,
        'Q16A': lambda a, b: 0.5 if a and b else 0,
        'Q19A': lambda a, b: 0.5 if a and b else 0,
        'Q20A': lambda a, b: 0.5 if a and b else 0,
        'Q46A': lambda a, b: 0.5 if a and b else 0,
        'Q46B': lambda a, b: 0.5 if a and b else 0,
        'Q52A': lambda a, b: 0.5 if a and b else 0,
        'Q57A': lambda a, b: 0.5 if a and b else 0,
        'Q58A': lambda a, b: 0.5 if a and b else 0,
        'Q60A': lambda a, b: 2 if a and b else 0,
        'Q66A': lambda a, b: 0.5 if a and b else 0,
        'Q71A': lambda a, b: 0.5 if a and b else 0,
        'Q72A': lambda a, b: 0.5 if a and b else 0,
        'Q74A': lambda a, b: 0.5 if a and b else 0,
        'Q79B': lambda a, b: 0.5 if a and b else 0,
        'Q87A': lambda a, b: 0.5 if a and b else 0,
        'Q9A': lambda a, b: 2 if a and b else 0,
        'Q87B': lambda a, b: -0.5 if a and b else 0,
    },
    'Q79B': {
        'Q35A': lambda a, b: 0.5 if a and b else 0,
        'Q36A': lambda a, b: 2 if a and b else 0,
        'Q46A': lambda a, b: 0.5 if a and b else 0,
        'Q46B': lambda a, b: 0.5 if a and b else 0,
        'Q50A': lambda a, b: 0.5 if a and b else 0,
        'Q51A': lambda a, b: 0.5 if a and b else 0,
        'Q52A': lambda a, b: 0.5 if a and b else 0,
        'Q53A': lambda a, b: 0.5 if a and b else 0,
        'Q54A': lambda a, b: 0.5 if a and b else 0,
        'Q55A': lambda a, b: 0.5 if a and b else 0,
        'Q56A': lambda a, b: 0.5 if a and b else 0,
        'Q60A': lambda a, b: 0.5 if a and b else 0,
        'Q69A': lambda a, b: 0.5 if a and b else 0,
        'Q74A': lambda a, b: 0.5 if a and b else 0,
        'Q18A': lambda a, b: -0.5 if a and b else 0,
        'Q32A': lambda a, b: -0.5 if a and b else 0,
        'Q49A': lambda a, b: -0.5 if a and b else 0,
        'Q87A': lambda a, b: -0.5 if a and b else 0,
    },
    'Q80A': {
        'Q88A': lambda a, b: 0.5 if a and b else (-0.5 if not a and b else 0),
        'Q53A': lambda a, b: 0.5 if a and b else 0,
        'Q52A': lambda a, b: 0.5 if a and b else 0,
        'Q87B': lambda a, b: -0.5 if a and b else 0,
        'Q83A': lambda a, b: 0.5 if a and b else 0,
        'Q80A': lambda a, b: -0.5 if a and b else 0,
        'Q75A': lambda a, b: 0.5 if a and b else 0,
        'Q78A': lambda a, b: 0.5 if a and b else 0,
        'Q65A': lambda a, b: 0.5 if a and b else 0,
        'Q2A': lambda a, b: 0.5 if a and b else 0,
        'Q61A': lambda a, b: -2 if a and b else 0,
        'Q41A': lambda a, b: -2 if a and b else 0,
        'Q40A': lambda a, b: -2 if a and b else 0,
    },
    'Q81A': {
        'Q65A': lambda a, b: 1 if not a and b else (-2 if a and b else 0),
        'Q1A': lambda a, b: 1 if a and b else 0,
        'Q33A': lambda a, b: 1 if a and b else 0,
        'Q48A': lambda a, b: 1 if a and b else 0,
        'Q50A': lambda a, b: 1 if a and b else 0,
        'Q52A': lambda a, b: 1 if a and b else 0,
        'Q53A': lambda a, b: 1 if a and b else 0,
        'Q56A': lambda a, b: 1 if a and b else 0,
        'Q58A': lambda a, b: 1 if a and b else 0,
        'Q61A': lambda a, b: 2 if a and b else 0,
        'Q66A': lambda a, b: 1 if a and b else 0,
        'Q67A': lambda a, b: 1 if a and b else 0,
        'Q74A': lambda a, b: 1 if a and b else 0,
        'Q78B': lambda a, b: 1 if a and b else 0,
        'Q81B': lambda a, b: 1 if a and b else 0,
        'Q87A': lambda a, b: 1 if a and b else 0,
        'Q84A': lambda a, b: -1 if a and b else 0,
    },
    'Q81B': {
        'Q61A': lambda a, b: 2 if not a and b else 0,
        'Q65A': lambda a, b: 2 if not a and b else (-2 if a and b else 0),
        'Q50A': lambda a, b: 1 if a and b else 0,
        'Q67A': lambda a, b: 1 if a and b else 0,
        'Q74A': lambda a, b: 2 if a and b else 0,
    },
    'Q82A': {
        'Q71A': lambda a, b: 2 if a and b else 0,
        'Q57A': lambda a, b: 0.5 if a and b else 0,
        'Q34A': lambda a, b: 0.5 if a and b else 0,
        'Q31A': lambda a, b: 0.5 if a and b else 0,
        'Q87A': lambda a, b: 0.5 if a and b else 0,
        'Q64A': lambda a, b: 0.5 if a and b else 0,
        'Q38A': lambda a, b: -2 if a and b else 0,
        'Q62A': lambda a, b: -2 if a and b else 0,
        'Q15A': lambda a, b: -2 if a and b else 0,
        'Q72A': lambda a, b: 2 if a and b else 0,
    },
    'Q83A': {
        'Q66A': lambda a, b: 1 if a and b else 0,
        'Q53A': lambda a, b: 1 if a and b else 0,
        'Q52A': lambda a, b: 1 if a and b else 0,
        'Q67A': lambda a, b: 1 if a and b else 0,
        'Q83A': lambda a, b: 1 if a and b else 0,
        'Q33A': lambda a, b: 1 if a and b else 0,
        'Q80A': lambda a, b: 1 if a and b else 0,
        'Q78B': lambda a, b: 1 if a and b else 0,
        'Q73A': lambda a, b: 1 if a and b else 0,
        'Q75A': lambda a, b: 1 if a and b else 0,
        'Q48A': lambda a, b: 1 if a and b else 0,
        'Q47B': lambda a, b: 1 if a and b else 0,
        'Q78A': lambda a, b: 1 if a and b else 0,
        'Q11A': lambda a, b: 1 if a and b else 0,
        'Q10A': lambda a, b: 1 if a and b else 0,
        'Q12A': lambda a, b: -2 if a and b else 0,
        'Q72A': lambda a, b: 2 if a and b else 0,
    },
    'Q84A': {
        'Q65A': lambda a, b: -1 if a and b else 0,
        'Q67A': lambda a, b: 1 if a and b else 0,
        'Q57A': lambda a, b: 1 if a and b else 0,
        'Q66A': lambda a, b: 1 if a and b else 0,
        'Q78B': lambda a, b: 2 if a and b else 0,
        'Q87A': lambda a, b: 1 if a and b else 0,
        'Q48A': lambda a, b: 1 if a and b else 0,
        'Q42A': lambda a, b: -1 if a and b else 0,
        'Q81B': lambda a, b: -1 if a and b else 0,
        'Q50A': lambda a, b: 2 if a and b else 0,
        'Q10A': lambda a, b: 1 if a and b else 0,
    },
    'Q85A': {
        'Q85A': lambda a, b: 0.5 if a and b else 0,
        'Q33A': lambda a, b: 2 if a and b else 0,
        'Q76A': lambda a, b: -2 if a and b else 0,
        'Q75A': lambda a, b: 0.5 if a and b else 0,
        'Q1A': lambda a, b: -0.5 if a and b else 0,
    },
    'Q86A': {
        'Q31A': lambda a, b: 0.5 if a and b else 0,
        'Q33A': lambda a, b: 0.5 if a and b else 0,
        'Q54A': lambda a, b: 0.5 if a and b else 0,
        'Q56A': lambda a, b: 0.5 if a and b else 0,
        'Q60A': lambda a, b: 0.5 if a and b else 0,
        'Q71A': lambda a, b: 0.5 if a and b else 0,
        'Q78A': lambda a, b: 0.5 if a and b else 0,
        'Q78B': lambda a, b: 0.5 if a and b else 0,
        'Q86B': lambda a, b: 0.5 if a and b else 0,
        'Q87A': lambda a, b: 0.5 if a and b else 0,
        'Q1A': lambda a, b: -0.5 if a and b else 0,
        'Q46B': lambda a, b: -0.5 if a and b else 0,
    },
    'Q86B': {
        'Q12A': lambda a, b: 2 if a and b else 0,
        'Q19A': lambda a, b: 2 if a and b else 0,
        'Q1A': lambda a, b: 0.5 if a and b else 0,
        'Q20A': lambda a, b: 0.5 if a and b else 0,
        'Q31A': lambda a, b: 0.5 if a and b else 0,
        'Q37A': lambda a, b: 0.5 if a and b else 0,
        'Q45A': lambda a, b: 0.5 if a and b else 0,
        'Q47A': lambda a, b: 0.5 if a and b else 0,
        'Q50A': lambda a, b: 0.5 if a and b else 0,
        'Q51A': lambda a, b: 0.5 if a and b else 0,
        'Q52A': lambda a, b: 0.5 if a and b else 0,
        'Q54A': lambda a, b: 0.5 if a and b else 0,
        'Q56A': lambda a, b: 0.5 if a and b else 0,
        'Q69A': lambda a, b: 0.5 if a and b else 0,
        'Q75A': lambda a, b: 0.5 if a and b else 0,
        'Q2A': lambda a, b: -0.5 if a and b else 0,
        'Q47B': lambda a, b: -0.5 if a and b else 0,
        'Q76A': lambda a, b: -2 if a and b else 0,
    },
    'Q87A': {
        'Q10A': lambda a, b: 0.5 if a and b else 0,
        'Q19A': lambda a, b: 0.5 if a and b else 0,
        'Q30A': lambda a, b: 0.5 if a and b else 0,
        'Q31A': lambda a, b: 2 if a and b else 0,
        'Q33A': lambda a, b: 0.5 if a and b else 0,
        'Q36A': lambda a, b: 0.5 if a and b else 0,
        'Q37A': lambda a, b: 0.5 if a and b else 0,
        'Q50A': lambda a, b: 0.5 if a and b else 0,
        'Q51A': lambda a, b: 0.5 if a and b else 0,
        'Q54A': lambda a, b: 0.5 if a and b else 0,
        'Q55A': lambda a, b: 2 if a and b else 0,
        'Q56A': lambda a, b: 2 if a and b else 0,
        'Q60A': lambda a, b: 2 if a and b else 0,
        'Q61A': lambda a, b: 2 if a and b else 0,
        'Q62A': lambda a, b: 0.5 if a and b else 0,
        'Q74A': lambda a, b: 2 if a and b else 0,
        'Q78A': lambda a, b: 0.5 if a and b else 0,
        'Q79A': lambda a, b: 0.5 if a and b else 0,
        'Q81A': lambda a, b: 0.5 if a and b else 0,
        'Q82A': lambda a, b: 0.5 if a and b else 0,
        'Q84A': lambda a, b: 0.5 if a and b else 0,
        'Q86A': lambda a, b: 0.5 if a and b else 0,
        'Q89A': lambda a, b: 0.5 if a and b else 0,
        'Q46B': lambda a, b: -0.5 if a and b else 0,
        'Q78B': lambda a, b: -2 if a and b else 0,
        'Q15A': lambda a, b: -0.5 if a and b else 0,
        'Q18A': lambda a, b: -0.5 if a and b else 0,
        'Q34A': lambda a, b: -0.5 if a and b else 0,
        'Q70A': lambda a, b: -0.5 if a and b else 0,
        'Q76A': lambda a, b: -2 if a and b else 0,
        'Q79B': lambda a, b: -0.5 if a and b else 0,
    },
    'Q87B': {
        'Q78A': lambda a, b: 0.5 if a and b else 0,
        'Q88A': lambda a, b: 0.5 if a and b else 0,
        'Q51A': lambda a, b: -0.5 if a and b else 0,
        'Q76A': lambda a, b: -2 if a and b else 0,
        'Q79A': lambda a, b: -0.5 if a and b else 0,
        'Q80A': lambda a, b: -0.5 if a and b else 0,
    },
    'Q88A': {
        'Q78B': lambda a, b: 1 if a and b else 0,
        'Q87A': lambda a, b: 1 if a and b else 0,
        'Q49A': lambda a, b: 1 if a and b else 0,
        'Q53A': lambda a, b: 1 if a and b else 0,
        'Q80A': lambda a, b: 1 if a and b else 0,
        'Q76A': lambda a, b: -1 if a and b else 0,
        'Q15A': lambda a, b: 1 if a and b else 0,
        'Q75A': lambda a, b: 1 if a and b else 0,
        'Q71A': lambda a, b: 1 if a and b else 0,
        'Q67A': lambda a, b: 1 if a and b else 0,
        'Q61A': lambda a, b: 1 if a and b else 0,
        'Q21A': lambda a, b: 1 if a and b else 0,
        'Q66A': lambda a, b: 1 if a and b else 0,
        'Q16A': lambda a, b: 2 if a and b else 0,
        'Q14A': lambda a, b: 2 if a and b else 0,
        'Q12A': lambda a, b: 2 if a and b else 0,
        'Q45A': lambda a, b: 1 if a and b else 0,
        'Q58A': lambda a, b: 1 if a and b else 0,
        'Q9A': lambda a, b: 1 if a and b else 0,
    },
    'Q89A': {
        'Q62A': lambda a, b: 0.5 if a and b else 0,
        'Q41A': lambda a, b: 2 if a and b else 0,
        'Q87A': lambda a, b: 0.5 if a and b else 0,
        'Q40A': lambda a, b: 0.5 if a and b else 0,
        'Q56A': lambda a, b: 0.5 if a and b else 0,
        'Q76A': lambda a, b: -0.5 if a and b else 0,
        'Q2A': lambda a, b: -0.5 if a and b else 0,
        'Q61A': lambda a, b: 2 if a and b else 0,
        'Q77A': lambda a, b: 0.5 if a and b else 0,
        'Q11A': lambda a, b: 0.5 if a and b else 0,
        'Q74A': lambda a, b: 0.5 if a and b else 0,
    }
}
