name: Publish
on:
  workflow_dispatch:
jobs:
  publish:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout application
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pipenv
    - name: Generate requirements.txt
      run: |
        pipenv lock -r > requirements.txt
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: unnecessary
    - name: Adding Known Hosts
      run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    - name: Deploy with rsync
      run: rsync -avz -e "ssh -p ${{ secrets.SSH_PORT }}" ./Pipfile ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/baggageclaimmatc/baggageclaim/
